FROM balenalib/%%BALENA_ARCH%%-alpine:3.12-run

RUN apk add device-mapper e2fsprogs bash

COPY create-device-mapper.sh /usr/bin/create-device-mapper.sh
RUN chmod +x /usr/bin/create-device-mapper.sh

COPY entrypoint.sh /usr/bin/entrypoint.sh
RUN chmod +x /usr/bin/entrypoint.sh

ENTRYPOINT ["/usr/bin/entrypoint.sh"]
CMD ["sleep", "infinity"]