#!/bin/sh

rce --restart=false -s btrfs -d -g /var/lib/rce  > /dev/null 2>&1 &

# Wait for rce to become ready
echo "Waiting for rce to become ready.."
while [ ! -S /var/run/rce.sock ]
do
	sleep 1
done

# Remove supervisor from previous boot.
# We have to make sure nobody started it before removing.
rce stop resin_supervisor || true
rce rm --force resin_supervisor || true

# Touch the resolv.conf file before running rce-run-supervisor.
touch /etc/resolv.conf

# Run supervisor
echo "Starting Supervisor.."
rce-run-supervisor

source /sbin/resin-vars
export API_ENDPOINT CONFIG_PATH
resin-device-progress "" "Finished" || true

while [ ! -d /resin-data/resin-supervisor ]
do
	sleep 1
done

# Disable power management.
iwconfig wlan0 power off

# Open socket for supervisor to connect to the host
bash -c 'while true; do rm -f /resin-data/resin-supervisor/host; socat UNIX-LISTEN:/resin-data/resin-supervisor/host EXEC:/bin/bash,pty,setsid,setpgid,stderr,ctty; done' &
