#!/bin/sh
#
# Enable/disable persistent logging based on config.json settings.
#

set -e

# Parse arguments
if [ $# -gt 0 ]; then
    cmd=$1
    shift
fi

. /usr/libexec/os-helpers-logging
. /usr/sbin/balena-config-vars

if [ "${cmd}" = "start" ]; then
    if [ "$PERSISTENT_LOGGING" = "true" ]; then
        mkdir -p /var/log/journal
        systemctl start bind-var-log-journal.service
        journalctl --flush
        info "Persistent logging activated."
    elif [ "$PERSISTENT_LOGGING" = "false" ]; then
        info "Persistent logging was deactivated."
        journalctl --sync
        systemctl stop systemd-journald.service
        systemctl stop bind-var-log-journal.service
        systemctl start systemd-journald.service
    fi
elif [ "${cmd}" = "stop" ]; then
    if [ "$PERSISTENT_LOGGING" = "true" ]; then
        journalctl --sync
        systemctl stop bind-var-log-journal.service
    fi
else
    error "Unknown command."
fi
