#!/bin/sh

# Copyright 2019 Balena Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o pipefail

dev=$1
uuid=$2

# shellcheck disable=SC1091
. /usr/libexec/os-helpers-fs

# Only when root is mounted we can differenciate
ROOT_MOUNTED=$(findmnt --output LABEL | grep -c resin-root)
if [ "$ROOT_MOUNTED" -eq 0 ]; then
    exit 1
fi

for mountpoint in $(findmnt --noheadings --output TARGET "$dev"); do
    if [ "$mountpoint" = "/" ] || [ "$mountpoint" = "/mnt/sysroot/active" ]; then
        echo 'RESIN_UPDATE_STATE=active'
        exit 0
    fi
done

if check_cmdline_uuids && ! check_cmdline_uuid "$uuid"; then
    # If the cmdline passed uuids and the current uuid is not part of it, we
    # don't create any udev links - consider it a label conflict
    exit 0
fi
echo 'RESIN_UPDATE_STATE=inactive'
