#!/bin/sh

# shellcheck disable=SC1091
. /usr/libexec/os-helpers-logging
. /usr/sbin/balena-config-defaults

get_bootenv() {
    BOOTENV_FILE="$1"
    KEY="$2"

    grub-editenv "${BOOTENV_FILE}" list | grep "^${KEY}=" | sed -e "s,^${KEY}=\(.*\)$,\1,"
}

abroot_enabled() {
    # Only run this inside the balena bootloader
    # shellcheck disable=SC2154
    if [ "$bootparam_balena_stage2" != "true" ]
    then
        return 1
    fi

    # shellcheck disable=SC2154
    if [ "$bootparam_flasher" = "true" ]
    then
        return 1
    fi

    # BOOTENV_FILE must be defined and exist
    if [ -z "${BOOTENV_FILE}" ] || [ ! -f "${BOOTENV_FILE}" ]
    then
        return 1
    fi

    # BOOT_DEV must be defined and exist
    if [ -z "${BOOT_DEV}" ] || [ ! -b "${BOOT_DEV}" ]
    then
        return 1
    fi

    return 0
}

abroot_run() {
    ROOT_PART=$(get_bootenv "${BOOTENV_FILE}" "resin_root_part")
    BOOT_COUNT=$(get_bootenv "${BOOTENV_FILE}" "bootcount")
    UPGRADE_AVAILABLE=$(get_bootenv "${BOOTENV_FILE}" "upgrade_available")

    if [ "${UPGRADE_AVAILABLE}" -eq 1 ]; then
        BOOT_COUNT=$(( BOOT_COUNT + 1 ))
        grub-editenv "${BOOTENV_FILE}" set "bootcount=${BOOT_COUNT}"
    fi

    # Rollback if this is the 3rd boot attempt
    IS_ROLLBACK="0"
    if [ "${BOOT_COUNT}" -ge 3 ]; then
        IS_ROLLBACK="1"
        if [ "${ROOT_PART}" = "A" ]; then
            ROOT_PART="B"
        else
            ROOT_PART="A"
        fi
    fi

    ROOT_UUID=$(lsblk -nlo uuid,label "${BOOT_DEV}" | grep "\(balena\|resin\)-root${ROOT_PART}" | cut -f1 -d " ")

    # Switch between rootA and rootB
    export bootparam_root="UUID=${ROOT_UUID}"

    # Some device types need additional rollback hooks after abroot,
    # let them know whether we're rolling back or not
    # and which partition we're going to boot from (after rollback)
    export IS_ROLLBACK
    export ROOT_PART
}
