#!/bin/sh

bootchart_enabled() {
	# shellcheck disable=SC2154
	[ "${bootparam_bootchart}" = "true" ] && return 0 || return 1
}

bootchart_run() {
	# bootchart runs backgrounded through switch_root, after the real root
	# is mounted and init is run, until it's collected enough samples, at
	# which point it exits
	#
	# argv[0][0] is replaced with '@' in main() to indicate that the
	# process remains from the initramfs, and to prevent init from killing
	# it
	#
	# https://freedesktop.org/wiki/Software/systemd/RootStorageDaemons/
	( exec /lib/systemd/systemd-bootchart ) &
}
