#!/bin/sh
# Copyright (C) 2011 O.S. Systems Software LTDA.
# Licensed on MIT

finish_enabled() {
    # shellcheck disable=SC2154
    if [ "$bootparam_recovery" = "true" ]; then
        if [ -n "${ADBD_PID}" ]; then
            # adbd is not a child process so cannot wait
            while kill -0  "${ADBD_PID}" 2>/dev/null; do sleep 1; done
        fi
    fi
    return 0
}

finish_run() {
    if [ -n "$ROOTFS_DIR" ]; then
        if [ ! -d $ROOTFS_DIR/dev ]; then
            fatal "ERROR: There's no '/dev' on rootfs."
        fi

        info "Switching root to '$ROOTFS_DIR'..."

        debug "Moving /dev, /proc and /sys onto rootfs..."
        mount --move /dev $ROOTFS_DIR/dev
        mount --move /sys $ROOTFS_DIR/sys

	# remount proc in $ROOTFS_DIR instead of moving if systemd-bootchart is
	# running, as it reads from /proc/schedstat
	if pgrep systemd-bootchart; then
		mount -t proc proc $ROOTFS_DIR/proc
	else
		mount --move /proc $ROOTFS_DIR/proc
	fi

        cd $ROOTFS_DIR
        exec switch_root $ROOTFS_DIR ${bootparam_init:-/sbin/init}
    else
        debug "No rootfs has been set"
    fi
}
