#!/bin/sh

#
# Flashes removable media like an SDcard
#

# shellcheck disable=SC1091
. /usr/libexec/os-helpers-logging

flasher_enabled() {
	# shellcheck disable=SC2154
	if [ "$bootparam_networkflasher" = "true" ]; then
		info "Network flasher detected."
		return 0
	fi
	return 1
}

flasher_run() {
	# This reboots at the end, no need to do anything else
	resin-init-flasher
}
