#!/bin/sh

fsck_enabled() {
    # On flasher we don't run fsck
    # shellcheck disable=SC2154
    if [ "$bootparam_flasher" = "true" ]; then
        echo "[INFO] Flasher detected. We don't run fsck on the partitions when provisioning."
        return 1
    fi
    return 0
}

fsck_run() {
    cat > "/etc/e2fsck.conf" <<EOF
[options]
broken_system_clock=1
EOF

    # fsck uses mtab to see if a device is mounted
    if [ ! -e "/etc/mtab" ]; then
        ln -sf /proc/mounts /etc/mtab
    fi

    info "Running filesystem checks on boot, rootA, rootB and state partitions."
    fsck.vfat -a -w "$(get_cmdline_uuid_label_path "resin-boot")"
    fsck.ext4 -p "$(get_cmdline_uuid_label_path "resin-rootA")"
    fsck.ext4 -p "$(get_cmdline_uuid_label_path "resin-rootB")"
    fsck.ext4 -p "$(get_cmdline_uuid_label_path "resin-state")"
}
