#!/bin/sh

fsck_enabled() {
    # On flasher we don't run fsck
    if [ "$bootparam_flasher" = "true" ]; then
        echo "[INFO] Flasher detected. We don't run fsck on the partitions when provisioning."
        return 1
    fi

    cat > "/etc/e2fsck.conf" <<EOF
[options]
broken_system_clock=1
EOF

    return 0
}

fsck_run() {
    # fsck uses mtab to see if a device is mounted
    if [ ! -e "/etc/mtab" ]; then
        ln -sf /proc/mounts /etc/mtab
    fi
    fsck.vfat -a -w /dev/disk/by-label/resin-boot
    fsck.ext4 -p /dev/disk/by-label/resin-rootA
    fsck.ext4 -p /dev/disk/by-label/resin-rootB
    fsck.ext4 -p /dev/disk/by-label/resin-state

    # Correct GPT secondary header
    datapart=$(readlink -f /dev/disk/by-label/resin-data)
    datadev=$(lsblk $datapart -n -o PKNAME)
    if [ "gpt" = "$(blkid -o value -s PTTYPE /dev/$datadev)" ] &&
            ( sgdisk --verify /dev/$datadev | grep -q "[T|t]he secondary header" ) ; then
        msg "Moving secondary GPT header to the end of the disk."
        sgdisk --move-second-header /dev/$datadev
        partprobe
    fi
}
