#!/bin/sh

#
# Fetch balena image from TFTP server
#

# shellcheck disable=SC1091
. /usr/libexec/os-helpers-logging

imagefetch_enabled() {
	# shellcheck disable=SC2154
	if [ "${bootparam_networkflasher}" = "true" ]; then
		info "Network flasher detected."
		return 0
	fi
	return 1
}

# NETWORK_BOOT_SERVER is set in the dynamicip module
imagefetch_run() {
	# Fetch balena image from tftp
	mkdir /opt || exit 1
	. /etc/resin-init-flasher.conf
	BALENA_IMAGE=$(basename "${balena_tftp_image}")
	info "Fetching ${BALENA_IMAGE} from ${NETWORK_BOOT_SERVER}"
	if ! tftp -g -r "${balena_tftp_image}" -l "/opt/${RESIN_IMAGE}" "${NETWORK_BOOT_SERVER}"; then
		fail "Failed fetching balena image"
		exit 1
	fi

	BALENA_BOOT=$(basename "${balena_tftp_boot}")
	info "Fetching ${BALENA_BOOT} from ${NETWORK_BOOT_SERVER}"
	if ! tftp -g -r "${balena_tftp_boot}" -l "/opt/${BALENA_BOOT}" "${NETWORK_BOOT_SERVER}"; then
		fail "Failed fetching balena boot partition"
		exit 1
	fi
	mkdir -p "/mnt/boot"
	cd "/mnt/boot"
	tar xzf "/opt/${BALENA_BOOT}"
	# With resin-image-flasher file in place we would need to move config.json around
	rm -f "/mnt/boot/resin-image-flasher"
	rm -f "/opt/${BALENA_BOOT}"
}
