#!/bin/sh

FREESPACE_LIMIT=10

resindataexpander_enabled() {
    # On flasher avoid expanding partition
    # shellcheck disable=SC2154
    if [ "$bootparam_flasher" = "true" ]; then
        error "Flasher detected. Avoiding expand partition mechanism."
        return 1
    fi
    return 0
}

resindataexpander_run() {
    datapart=$(get_cmdline_uuid_label_path "resin-data")
    if ! wait4file "$datapart" "300"; then
	    error "Timeout while waiting for data partition to be detected. Data partition expansion will not be tried."
	    return
    fi

    # lsblk works on block devices only
    datadev=$(lsblk "$(readlink -f "$datapart")" -n -o PKNAME)
    for freespace in $(parted -m "/dev/$datadev" unit MiB print free | grep free | cut -d: -f4 | sed 's/MiB//g'); do
        if [ "$(echo "$freespace" \> $FREESPACE_LIMIT | bc -l)" = "1" ]; then
	        info "resindataexpander: Expand extended partition... "
	        parted -s "/dev/$datadev" -- resizepart 4 -1s
	        info "resindataexpander: Finished expanding extended partition."
	        info "resindataexpander: Expand data partition... "
	        parted -s "/dev/$datadev" -- resizepart 6 -1s
	        info "resindataexpander: Finished expanding data partition."
	        partprobe
	        sync
                # We return when we've done the expansion
                return
        fi
    done
    info "No data partition expanding needed."
}
