#!/bin/sh
#
# Copyright 2018 Resinio Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit

. /usr/sbin/resin-vars

echo "Rollback: Parsing bootloader configuration"

if [ ! -d "$RESIN_BOOT_MOUNTPOINT" ]; then
        echo "Rollback: $RESIN_BOOT_MOUNTPOINT doesn't exist."
        exit 1
fi

# Fetch bootloader variables into environment
if [ -f "${RESIN_BOOT_MOUNTPOINT}/resinOS_uEnv.txt" ]; then
	BOOTLOADER_FILE="${RESIN_BOOT_MOUNTPOINT}/resinOS_uEnv.txt"
else
	grub_cfg=$(find "${RESIN_BOOT_MOUNTPOINT}" -name grub.cfg)
	if [ -f "${grub_cfg}" ]; then
		BOOTLOADER_FILE="${grub_cfg}"
	fi
fi

# Parse bootloader config file for key variables
upgrade_available=`grep "upgrade_available=" "${BOOTLOADER_FILE}" | cut -d'=' -f 2`
resin_root_part=`grep "resin_root_part=" "${BOOTLOADER_FILE}" | cut -d'=' -f 2`

if [ -z "${upgrade_available}" ]; then
	echo "Rollback: Could not find upgrade_available variable in bootloader environment"
	exit 1
fi

if [ -z "${resin_root_part}" ]; then
	echo "Rollback: Could not find resin_root_part variable in bootloader environment"
	exit 1
fi

current_part=$(findmnt --noheadings --canonicalize --output SOURCE /mnt/sysroot/active)
blockdev=$(basename "$current_part")
current_part_idx=$(cat "/sys/class/block/$blockdev/partition")

# Partition numbers are in hex.
current_part_idx=$(printf "%x" $current_part_idx)
