#!/bin/sh
#
# Copyright 2018 Resinio Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit

. /usr/sbin/resin-vars
. /usr/bin/rollback-parse-bootloader

if [ "$resin_root_part" != "$current_part_idx" ]; then
	echo "Rollback: Looks like we are running in atlboot mode. Running hooks to recover bootfiles"
	DURING_UPDATE=0 /usr/bin/hostapp-update-hooks
	touch /mnt/state/rollback-altboot-triggered
	rollback-stop || true
	echo "Rollback: Rebooting system"
	sleep 10
	reboot
else
	echo "Rollback: Nothing to do by rollback-altboot.service"
	echo "Rollback: rollback-health.service will run sanity checks and remove breadcrumbs"
fi
