#!/bin/bash

#
# Script used to prepare supervisor running environment
#

set -o pipefail
set -e

echo "Mount /resin-data..."
if ! mount | grep /resin-data > /dev/null; then
    mount -o bind /mnt/data/resin-data /resin-data
fi

exit 0
