#!/bin/bash

#
# TEST: Query docker if supervisor is running
#

source /var/lib/resin/resin-tests/resin-tests

state=$(rce inspect --format="{{ .State.Running }}" resin_supervisor 2>&1)
if [ "$state" == "true" ]; then
    log FAIL $0
fi

log PASS $0
