#!/bin/bash

added_servers_file=/tmp/chrony_added_dhcp_ntp_servers

interface=$1
action=$2

case "$action" in
	dhcp4-change|up|connectivity-change)
	# Run resin-ntp-config to update chronyc from ntp servers in config.json
	/usr/bin/resin-ntp-config

	# Inform chrony we are online
	# We add a timeout as we have noticed this command being stuck in a loop eating cpu. Bug possibly resolved upstream. https://github.com/mlichvar/chrony/commit/6863e43269fe27ce2744eb643295f31c00ec176d#diff-50898f0cb35139d87132f4732a029213
	/usr/bin/timeout 10 /usr/bin/chronyc online || true

	if [[ -n $DHCP4_NTP_SERVERS ]]; then
		# Tell chronyd to use this server
		for ntp in ${DHCP4_NTP_SERVERS}; do
			/usr/bin/chronyc add server $ntp minpoll 14 maxpoll 14 || true
			/usr/bin/chronyc burst 4/10 "$ntp" || true
		done
		# Save the ntp server we received and interface information to a file
		echo "resin_$interface=\""""$DHCP4_NTP_SERVERS""\" >> $added_servers_file
	fi
	;;
	down)
		# Read ntp server information from file into env variables
		if [ -f $added_servers_file ]; then
			. $added_servers_file
			eval ntp_connection=\$"resin_$interface"

			# Delete the ntp server for that interface from file
			sed -i "/resin_$interface/d" $added_servers_file

			# Tell chronyd to remove this server
			for ntp in ${ntp_connection}; do
				# Only delete the server if it isn't being added by some other interface
				if ! grep -q "$ntp" $added_servers_file; then
					/usr/bin/chronyc delete $ntp || true
				fi

			done
		fi

	;;
	*)
	;;
esac
