#!/bin/sh

DATA_PARTITION=/dev/disk/by-label/resin-data
LABEL_TIMEOUT=30

# Waiting for the filesystem label
start="$(date +%s)"
end="$start"
while [ ! -L "$DATA_PARTITION" ]; do
	if [ $((end - start)) -le "$LABEL_TIMEOUT" ]; then
		sleep 1 && end=$((end + 1))
	else
		echo "[ERROR] Timeout while waiting for filesystem label to appear."
		return 1
	fi
done

echo "[INFO] Filesystem check on $DATA_PARTITION... "
e2fsck -y $DATA_PARTITION
echo "[INFO] Expand ext4 filesystem on $DATA_PARTITION... "
resize2fs -f $DATA_PARTITION
sync

exit 0
