#!/bin/sh

docker --restart=false -s btrfs --dns=8.8.8.8 --dns=8.8.4.4 -d -g /mnt/mmcblk0p8/docker  > /dev/null 2>&1 &

# Wait for docker to become ready
echo "Waiting for docker to become ready.."
while [ ! -S /var/run/docker.sock ]
do
	sleep 1
done

# Load the following modules:
modprobe leds-gpio  # Leds
modprobe snd-bcm2835 # Sound
#modprobe spi-bcm2708 # SPI
#modprobe i2c-bcm2708 # I2c
#modprobe i2c-dev #I2C

# Wait for internet connection TODO: Remove this by enabling watchdog inside supervisor.
while true; do
                ret=0
                ping -c 1 -w 1 www.google.com || ret=$?
                [ $ret -eq 0 ] && break
                sleep 1
done

# Open socket for supervisor to connect to the host
bash -c 'while true; do rm -f /resin-data/resin-supervisor/host; socat UNIX-LISTEN:/resin-data/resin-supervisor/host EXEC:/bin/bash,pty,setsid,setpgid,stderr,ctty; done' &

# Run supervisor
echo "Starting resin/rpi-supervisor.."
docker run --privileged -d -v /var/run/docker.sock:/run/docker.sock resin/rpi-supervisor /start
