#!/bin/sh

docker --restart=false -s btrfs -d -g /var/lib/docker &

# Wait for docker to become ready
echo "Waiting for docker to become ready.."
while [ ! -S /var/run/docker.sock ]
do
	sleep 1
done

# Run supervisor
echo "Starting Supervisor.."
docker-run-supervisor

source /etc/resin.conf
export API_ENDPOINT CONFIG_PATH
resin-device-progress "" "Finished" || true

while [ ! -d /resin-data/resin-supervisor ]
do
	sleep 1
done

# Disable power management.
iwconfig wlan0 power off

# Open socket for supervisor to connect to the host
bash -c 'while true; do rm -f /resin-data/resin-supervisor/host; socat UNIX-LISTEN:/resin-data/resin-supervisor/host EXEC:/bin/bash,pty,setsid,setpgid,stderr,ctty; done' &
