#!/bin/sh
#
# Copyright 2018 Balena Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit

. /usr/sbin/resin-vars
. /usr/bin/rollback-parse-bootloader

if [ -f "/mnt/state/rollback-altboot-breadcrumb" ]; then
	echo "Rollback: Clearing bootcount"
	# Clear grub bootcount
	grub_env=$(find "${RESIN_BOOT_MOUNTPOINT}" -name grubenv)
	if [ -f "${grub_env}" ]; then
		sed -i "s#bootcount=.*#bootcount=0 #g" "${grub_env}" || true
	else
		# Clear u-boot bootcount
		rm -f "${RESIN_BOOT_MOUNTPOINT}/bootcount.env" || true
	fi

	sync -f "${RESIN_BOOT_MOUNTPOINT}"
	echo "Rollback: Bootcount cleared"
fi
