#!/bin/bash

help () {
    cat << EOF
Generate uuid for a new resin device
resin-device-uuid [options]

Options:
    -h, --help
        Display this help and exit.

    -c, --config-path CONFIG_PATH
        Use a non default config.json file.
        This argument is passed to resin-vars script.
EOF
}

# Parse arguments
while [[ $# > 0 ]]; do
    key=$1
    case $key in
        -h|--help)
            help
            exit 0
            ;;
        -c|--config-path)
            CONFIG_PATH=$2
            shift
            ;;
        *)
            echo "[WARNING] $0 : Argument '$1' unknown. Ignoring."
            ;;
    esac
    shift
done

source /usr/sbin/resin-vars --config-path $CONFIG_PATH

if [ -z "$CONFIG_PATH" ]; then
    echo "[ERROR] resin-device-uuid : Please set CONFIG_PATH environment variable."
    exit 1
fi

if [ ! -s "$CONFIG_PATH" ]; then
    echo "[INFO] resin-device-uuid: Config file is missing. Creating.."
    echo '{}' > $CONFIG_PATH
else
    read uuid <<<$(jq -r '.uuid //empty' $CONFIG_PATH)
fi

if [ -z "$uuid" ]; then
    echo "[INFO] resin-device-uuid: UUID missing from config file. Generating..."
    uuid=$(openssl rand -hex 31)
    echo $(cat $CONFIG_PATH | jq ".uuid=\"$uuid\"") > $CONFIG_PATH
else
    echo "[INFO] resin-device-uuid : Device already has uuid assigned."
fi

exit 0
