#!/bin/bash

help () {
    cat << EOF
Generate unique key for a new resin device
resin-unique-key [options] <key name>

Options:
    -h, --help
        Display this help and exit.

    -c, --config-path CONFIG_PATH
        Use a non default config.json file.
        This argument is passed to resin-vars script.
EOF
}

# Parse arguments
while [ $# -gt 0 ]; do
    key=$1
    case $key in
        -h|--help)
            help
            exit 0
            ;;
        -c|--config-path)
            CONFIG_PATH=$2
            shift
            ;;
        *)
            key_name=$1
            ;;
    esac
    shift
done

source /usr/sbin/resin-vars --config-path "$CONFIG_PATH"

if [ -z "$CONFIG_PATH" ]; then
    echo "[ERROR] resin-unique-key : Please set CONFIG_PATH environment variable."
    exit 1
fi

if [ ! -s "$CONFIG_PATH" ]; then
    echo "[INFO] resin-unique-key: Config file is missing. Creating.."
    echo '{}' > "$CONFIG_PATH"
else
    read key <<<$(jq -r ".$key_name //empty" "$CONFIG_PATH")
fi

if [ -z "$key" ]; then
    echo "[INFO] resin-unique-key: $key_name missing from config file. Generating..."
    key=$(openssl rand -hex 16)
    generated_json=$(jq ".$key_name=\"$key\"" "$CONFIG_PATH")
    echo "$generated_json" > "$CONFIG_PATH"
else
    echo "[INFO] resin-unique-key : Device already has $key_name assigned."
fi

exit 0
