BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "balena-wrynose"
BBFILE_PATTERN_balena-wrynose := "^${LAYERDIR}/"
BBFILE_PRIORITY_balena-wrynose = "1337"

LAYERSERIES_COMPAT_balena-wrynose = "wrynose"

