#!/bin/bash
if [ "$#" -ne 2 ]; then
	echo "Usage: $0 API_ENDPOINT CONFIG_PATH"
	echo -e "\tAPI_ENDPOINT\tExample: https://staging.resin.io"
	echo -e "\tCONFIG_PATH\tExample: /boot/config.json"
	exit 1
fi

API_ENDPOINT=$1
CONFIG_PATH=$2

if [ `jq ".uuid | length" $CONFIG_PATH` -eq 0 ]; then
	echo "UUID missing from config file, device register cannot continue."
	exit 1
fi

while true; do
	if curl -sL -w '%{http_code}' $API_ENDPOINT/ping -o /dev/null | egrep "20[0-9]|30[0-9]" >/dev/null
	then
		read api_key user_id application_id uuid device_type <<<$(jq -r '.apiKey,.userId,.applicationId,.uuid,.deviceType // "Raspberry Pi"' $CONFIG_PATH)

		status_code=$(curl -s -X POST -w "%{http_code}" \
				   -o /dev/null
				   -d "user=$user_id" \
				   -d "application=$application_id" \
				   -d "uuid=$uuid"  \
				   --data-urlencode "device_type=$device_type" \
				   "$API_ENDPOINT/ewa/device?apikey=$api_key")

		if [ "$status_code" -eq 201 ]; then
			config_json=`cat $CONFIG_PATH`
			echo $config_json | jq ".registered_at=\"`date +%s`\"" > $CONFIG_PATH
			echo "Registered device with UUID: $uuid."
		else
			echo "Failed to register device. Status code: $status_code"
		fi
		break
	else
		echo  "Not connected. Trying again..."
		sleep 2
	fi
done
