#!/bin/sh
set -e

mkdir -p /mnt/mmcblk0p1 
mount /dev/mmcblk0p1 /mnt/mmcblk0p1


if [ -e /mnt/mmcblk0p1/resin/network/network.config ]; then
	# Remove old Connman Settings
	rm -rf /var/lib/connman/*
        # Copy Connman settings
        cp -r /mnt/mmcblk0p1/resin/network/network.config /var/lib/connman/network.config
	if [ -e /mnt/mmcblk0p1/resin/network/settings ]; then
		cp -r /mnt/mmcblk0p1/resin/network/settings /var/lib/connman/settings
	fi
fi

mkdir -p /mnt/mmcblk0p5
mount /dev/mmcblk0p5 /mnt/mmcblk0p5

if [ ! -e /mnt/mmcblk0p5/remove_to_reset_data ]; then

	# Format the volume to hold our images.
	mkfs.btrfs -f /dev/mmcblk0p8
	mkdir -p /mnt/mmcblk0p8
	mount /dev/mmcblk0p8 /mnt/mmcblk0p8
	
	# Make swap
	mkswap /dev/mmcblk0p7
	
	# Load the supervisor
	# tar -xf /mnt/mmcblk0p1/resin/docker_root.tar -C /mnt/mmcblk0p8
	mkdir -p /mnt/mmcblk0p8/docker/btrfs/subvolumes
	cp /mnt/mmcblk0p1/resin/resin-rpi-supervisor/repositories /mnt/mmcblk0p8/docker/repositories-btrfs
	cd /mnt/mmcblk0p8/docker/btrfs/subvolumes
	filename='/mnt/mmcblk0p1/resin/resin-rpi-supervisor/history.list'
	parent="0"
	while read p; do
	    if [ $parent == "0" ]
	    then
		echo "Creating Subvolume"
		btrfs subvolume create $p
	    else
		echo "Creating Snapshot from parent"
		btrfs subvolume snapshot $parent $p
	    fi
	    tar -xf /mnt/mmcblk0p1/resin/resin-rpi-supervisor/$p/layer.tpxz -C $p
	    mkdir -p /mnt/mmcblk0p8/docker/graph/$p
	    cp -r /mnt/mmcblk0p1/resin/resin-rpi-supervisor/$p/json /mnt/mmcblk0p8/docker/graph/$p
            parent=$p
	done < $filename

	touch /mnt/mmcblk0p5/remove_to_reset_data
	sync

else
	# Mount docker images directory
	mount /dev/mmcblk0p8 /mnt/mmcblk0p8
fi

exit 0
