#!/bin/sh
set -e

mkdir -p /mnt/mmcblk0p1 
mount /dev/mmcblk0p1 /mnt/mmcblk0p1

if [ -e /mnt/mmcblk0p1/resin/connman.conf ]; then
	# Copy Connman settings
	mkdir -p /etc/connman/
	cp -r /mnt/mmcblk0p1/resin/connman.conf /etc/connman/main.conf
	/etc/init.d/connman restart

fi

mkdir -p /mnt/mmcblk0p5
mount /dev/mmcblk0p5 /mnt/mmcblk0p5

if [ ! -e /mnt/mmcblk0p5/remove_to_reset_data ]; then

	# Format the volume to hold our images.
	mkfs.btrfs -f /dev/mmcblk0p8
	mkdir -p /mnt/mmcblk0p8
	mount /dev/mmcblk0p8 /mnt/mmcblk0p8
	
	# Make swap
	mkswap /dev/mmcblk0p7
	
	# Load the supervisor
	tar -xf /mnt/mmcblk0p1/resin/docker_root.tar -C /mnt/mmcblk0p8
	cd /mnt/mmcblk0p8/docker/btrfs/subvolumes
	filename='/mnt/mmcblk0p1/resin/history.list'
	parent="0"
	while read p; do
	    if [ $parent == "0" ]
	    then
		echo "Creating Subvolume"
		btrfs subvolume create $p
	    else
		echo "Creating Snapshot from parent"
		btrfs subvolume snapshot $parent $p
	    fi
	    tar -xf /mnt/mmcblk0p1/resin/resin-rpi-supervisor/$p/layer.tar -C $p
            parent=$p
	done < $filename

	touch /mnt/mmcblk0p5/remove_to_reset_data
	sync

else
	# Mount docker images directory
	mount /dev/mmcblk0p8 /mnt/mmcblk0p8
fi

# Initialize swap
swapon /dev/mmcblk0p7
docker --restart=false -s btrfs -d -g /mnt/mmcblk0p8/docker &

# Wait for docker to become ready
echo "Waiting for docker to become ready.."
while [ ! -S /var/run/docker.sock ]
do
	sleep 1
done

# Delete all containers  
echo "Deleting all previous containers.."  
docker ps -qa | xargs docker rm || true  

# Load the following modules:
modprobe leds-gpio  # Leds
modprobe snd-bcm2835 # Sound
#modprobe spi-bcm2708 # SPI
#modprobe i2c-bcm2708 # I2c
#modprobe i2c-dev #I2C


# Run supervisor  
echo "Starting resin/rpi-supervisor.."  
docker run --privileged -d -v /mnt/mmcblk0p1/config.json:/boot/config.json -v /var/run/docker.sock:/run/docker.sock -v /mnt/mmcblk0p8/data:/data -e API_ENDPOINT=https://api.resin.io -e REGISTRY_ENDPOINT=registry.resin.io -e PUBNUB_SUBSCRIBE_KEY=sub-c-bbc12eba-ce4a-11e3-9782-02ee2ddab7fe -e PUBNUB_PUBLISH_KEY=pub-c-6cbce8db-bfd1-4fdf-a8c8-53671ae2b226 resin/rpi-supervisor /start

exit 0
