#!/bin/sh


# Wait for internet connection TODO: Remove this by enabling watchdog inside supervisor.
while true; do
                ret=0
                ping -c 1 -w 1 www.google.com || ret=$?
                [ $ret -eq 0 ] && break
                sleep 1
done



# Run supervisor  
echo "Starting resin/rpi-supervisor.."  
docker run --privileged -d -v /mnt/mmcblk0p1/config.json:/boot/config.json -v /var/run/docker.sock:/run/docker.sock -v /mnt/mmcblk0p8/data:/data -e API_ENDPOINT=https://api.resin.io -e REGISTRY_ENDPOINT=registry.resin.io -e PUBNUB_SUBSCRIBE_KEY=sub-c-bbc12eba-ce4a-11e3-9782-02ee2ddab7fe -e PUBNUB_PUBLISH_KEY=pub-c-6cbce8db-bfd1-4fdf-a8c8-53671ae2b226 resin/rpi-supervisor /start
