#!/bin/sh
#
# copy over NTP configuration
#

set -e

. /usr/sbin/resin-vars

if [ ! -f "$CONFIG_PATH" ]; then
	echo "balena-ntp-config: $CONFIG_PATH does not exist."
	exit 1
else
	echo "balena-ntp-config: Found config.json in $CONFIG_PATH ."
fi

if [ ! -z "$NTP_SERVERS" ]; then
	for ntp in ${NTP_SERVERS}; do
		/usr/bin/chronyc add server $ntp || true
	done
fi

exit 0
