#!/bin/sh

help () {
    cat << EOF
Script for setting resin shell environment
resin-vars [options]

Options:
    -h, --help
        Display this help and exit.

    -c, --config-path CONFIG_PATH
        Use a non default config.json file.
        Default: /mnt/boot/config.json
EOF
}

# Parse arguments
while [ "$#" -gt "0" ]; do
    key=$1
    case $key in
        -h|--help)
            help
            exit 0
            ;;
        -c|--config-path)
            CONFIG_PATH=$2
            shift
            ;;
        *)
            echo "[WARNING] $0 : Argument '$1' unknown. Ignoring."
            ;;
    esac
    shift
done

# Resin-boot mountpoint
BOOT_MOUNTPOINT="/mnt/boot"
FLASHER_FILEFLAG="$BOOT_MOUNTPOINT/resin-image-flasher"

# Default values
if [ -z "$CONFIG_PATH" ]; then
    if [ -f "$FLASHER_FILEFLAG" ]; then
        # Flasher stores a volatile file in tmpfs
        CONFIG_PATH=/mnt/boottmp/config.json
    else
        CONFIG_PATH=$BOOT_MOUNTPOINT/config.json
    fi
fi

RESIN_BOOT_MOUNTPOINT="/mnt/boot"

# If config.json provides redefinitions for our vars let us rewrite their
# runtime value
if [ -f $CONFIG_PATH ]; then
    eval "$(jq -r '@sh "
         API_ENDPOINT=\(.apiEndpoint // "")
         LISTEN_PORT=\(.listenPort // "")
         MIXPANEL_TOKEN=\(.mixpanelToken // "")
         DELTA_ENDPOINT=\(.deltaEndpoint // "")
         CONFIG_HOSTNAME=\(.hostname // "")
         PERSISTENT_LOGGING=\(.persistentLogging // "")
         COUNTRY=\(.country // "")
         UUID=\(.uuid // "")
         PROVISIONING_API_KEY=\(.apiKey // "")
         DEVICE_API_KEY=\(.deviceApiKey // "")
         DEVICE_ID=\(.deviceId // "")
         APPLICATION_ID=\(.applicationId // "")
         DEVICE_TYPE=\(.deviceType // "")
         REGISTERED_AT=\(.registered_at // "")
         NTP_SERVERS=\(.ntpServers // "")
         DNS_SERVERS=\(.dnsServers // "")
         BALENA_ROOT_CA=\(.balenaRootCA // "")
         "' $CONFIG_PATH)"

    # Various default values
    PERSISTENT_LOGGING=${PERSISTENT_LOGGING:-false}
    DNS_SERVERS=${DNS_SERVERS:-8.8.8.8}
    # Don't propagate the `null` value further to dnsmasq configuration
    if [ "$DNS_SERVERS" = "null" ]; then
        DNS_SERVERS=""
    fi
else
    echo "[WARNING] $0 : '$CONFIG_PATH' not found."
fi
