#!/bin/bash
set -x
#
# Script which burns an image from an external device to an internal device
# Assumptions:
#   * image is in boot partition of external device
#   * all needed variables are configured in resin-init-flasher.conf
#   * filesystems labeling scheme is persistent (flasher-*/resin-*)
# Variables in resin-init-flasher.conf
#  INTERNAL_DEVICE_KERNEL                 - internal device (enumerated by kernel) to be flashed
#                                             * it's impossible to known what dev to flash because
#                                               we don't have any labels before flashing something
#                                               so we need this info
#                                             * when multiple entries provided, the first block device
#                                               found will be used
#  INTERNAL_DEVICE_BOOTLOADER_CONFIG      - name of the bootloader config for internal media boot
#  INTERNAL_DEVICE_BOOTLOADER_CONFIG_PATH - relative path to internal boot partition where
#                                               INTERNAL_DEVICE_BOOTLOADER_CONFIG will be copied to
#  BALENA_IMAGE                            - image to be flashed on internal device
#                                             * this is defaulted to
#                                               balena-image-${MACHINE}.balenaos-img and should be
#                                               just fine
#  BOOTLOADER_FLASH_DEVICE                - device where bootloader binary will be flashed
#                                             * this variable should be set together with
#                                               BOOTLOADER_IMAGE
#                                             * if this variable is not set we DO NOT flash u-boot
#                                               to internal flash device
#  BOOTLOADER_IMAGE                       - name of the u-boot binary
#  BOOTLOADER_BLOCK_SIZE_OFFSET           - offset at which we write u-boot binary
#  BOOTLOADER_SKIP_OUTPUT_BLOCKS          - number of blocks to skip when writing bootloader
#                                             * this is the seek param to dd
#
#  Certain hardware requires that the bootloader is split into MLO and u-boot.img rather than having
# it all bundled in a u-boot.img binary. To address this requirement, this flashing script will further
# look for variables called BOOTLOADER_FLASH_DEVICE_1, BOOTLOADER_IMAGE_1, BOOTLOADER_BLOCK_SIZE_OFFSET_1,
# BOOTLOADER_SKIP_OUTPUT_BLOCKS_1 to be used in the same way as BOOTLOADER_FLASH_DEVICE, BOOTLOADER_IMAGE,
# BOOTLOADER_BLOCK_SIZE_OFFSET, BOOTLOADER_SKIP_OUTPUT_BLOCKS so that user can specify both MLO and u-boot
# to be written in the respective devices.

set -e

# Very long variables :)
BALENA_ROOT_MOUNTPOINT=${BALENA_ROOT_MOUNTPOINT:-}
EXTERNAL_DEVICE_BOOT_PART_MOUNTPOINT=${BALENA_BOOT_MOUNTPOINT}
FLASHER_CONF_FILE=${FLASHER_CONF_FILE:-"${BALENA_ROOT_MOUNTPOINT}/etc/resin-init-flasher.conf"}
SPLASH_DIRNAME=${SPLASH_DIRNAME:-splash}
BALENA_BOOTLOADER_CONFIG=${BALENA_BOOTLOADER_CONFIG:-resinOS_uEnv.txt}
INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT=/tmp/internal_boot
INTERNAL_DEVICE_CONF_PART_MOUNTPOINT=/tmp/internal_conf
CURRENT_ROOT=$(findmnt --noheadings --canonicalize --output SOURCE / | xargs lsblk -no pkname)
LUKS=0
SECUREBOOT_SETUP=0

function clean {
    echo "[resin-init-flasher] Cleanup."
    umount $INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT > /dev/null 2>&1 || true
    umount $INTERNAL_DEVICE_CONF_PART_MOUNTPOINT > /dev/null 2>&1 || true
}

function fail {
    echo "[resin-init-flasher] ERROR: $1"
    clean
    exit 1
}

function inform {
    echo "[resin-init-flasher] INFO: $1"
}

report_progress() {
    local _ratio="${1}"
    local _msg="${2}"
    if command -v resin-device-progress; then
        resin-device-progress --percentage "${_ratio}" --state "${_msg}" || true
    else
        inform "[${_ratio}%]: ${_msg}"
    fi
}

function dd_with_progress {
    SRC=$1
    DEST=$2
    OFFSET=$3
    TOTAL_SIZE=$4

    dd "if=$SRC" "of=$DEST" bs=4M 2> /tmp/dd_progress_log & DD_PID=$!

    if ! kill -0 $DD_PID; then
        # dd might have been too fast, let's check exit status if it is no longer running
        if ! ps | grep "^ *$DD_PID " && wait "$DD_PID"; then
            # dd is not running and the exitcode was 0, dd completed too fast to report progress
            return
        fi

        # Either dd is still running or exit status reported error
        fail "Failed to flash internal device $INTERNAL_DEVICE_KERNEL."
    fi

    # Give dd chance to register the signal handler
    # This was originally hidden behind determining image size
    sleep 1

    while kill -USR1 $DD_PID 2>/dev/null; do
        sleep 3
        if [ ! -s /tmp/dd_progress_log ]; then
            continue
        fi
        WRITTEN_BYTES=$(awk 'END{print $1}' /tmp/dd_progress_log)
        TOTAL_WRITTEN_BYTES=$["$WRITTEN_BYTES" + "$OFFSET"]
        let RATIO=$TOTAL_WRITTEN_BYTES*100/$TOTAL_SIZE || true
        report_progress "$RATIO" "Flashing balenaOS on internal media"
        truncate -s 0 /tmp/dd_progress_log
    done
}

########
# MAIN #
########

# Only root
if [ "$EUID" -ne 0 ]; then
    fail "Please run as root."
fi

inform "Board specific initialization..."
${BALENA_ROOT_MOUNTPOINT}/usr/bin/resin-init-board

# Balena configuration file
if [ -f ${BALENA_ROOT_MOUNTPOINT}/usr/sbin/balena-config-vars ]; then
    source ${BALENA_ROOT_MOUNTPOINT}/usr/sbin/balena-config-vars
fi

# Configuration file
if [ -f $FLASHER_CONF_FILE ]; then
    source $FLASHER_CONF_FILE
    inform "resin-init-flasher configuration found."
fi

# CONFIG_PATH should exist
if [ ! -f "$CONFIG_PATH" ]; then
    fail "$CONFIG_PATH : No such file."
fi

# BALENA_BOOT_MOUNTPOINT should exit
if [ ! -d "$BALENA_BOOT_MOUNTPOINT" ]; then
	fail "$BALENA_BOOT_MOUNTPOINT : No such directory."
fi

# Give a chance to openvpn to come alive
STARTTIME=$(date +%s)
ENDTIME="$STARTTIME"
TIMEOUT=15
if command -v systemclt; then
    while [ "$(systemctl is-active openvpn)" != "active" ]
    do
        if [ $((ENDTIME - STARTTIME)) -le $TIMEOUT ]; then
            sleep 1 && ENDTIME=$((ENDTIME + 1))
        else
            inform "Timeout while waiting for openvpn to come alive. No network?"
            break
        fi
    done
fi

# Flash Resin image on internal device
inform "Flash internal device... will take around 5 minutes... "
internal_dev=""
for d in $INTERNAL_DEVICE_KERNEL; do
    if [ "$CURRENT_ROOT" = "$d" ]; then
        inform "$d is our install media, skip it..."
        continue
    fi
    if fdisk -l | grep -q "$d"; then
        internal_dev=$d
        break
    fi
done
if [ -z "$internal_dev" ]; then
    report_progress 100 "Failed to find any block devices."
    fail "Failed to find any block devices in $INTERNAL_DEVICE_KERNEL."
fi
inform "$internal_dev will be used for flashing."

IMAGE_FILE_SIZE=$(wc -c "${BALENA_ROOT_MOUNTPOINT}/opt/$BALENA_IMAGE" | awk '{print $1}')

# Check for UEFI mode and set variables accordingly.
if [ -d ${BALENA_ROOT_MOUNTPOINT}/sys/firmware/efi ]; then
    SECUREBOOT_VAR=$(efivar -p -n 8be4df61-93ca-11d2-aa0d-00e098032b8c-SecureBoot | awk 'NR==1, $1 == "Value:" {next}; NF {print $2}')
    SETUPMODE_VAR=$(efivar -p -n 8be4df61-93ca-11d2-aa0d-00e098032b8c-SetupMode | awk 'NR==1, $1 == "Value:" {next}; NF {print $2}')
    if [ "$SECUREBOOT_VAR" -eq "1" ]; then
        LUKS=1
    fi
    if [ "$SETUPMODE_VAR" -eq "1" ]; then
        SECUREBOOT_SETUP=1
    fi
fi

if [ "$LUKS" = "1" ]; then
    # Include FS helpers for repartitioning
    . "${BALENA_ROOT_MOUNTPOINT}"/usr/libexec/os-helpers-fs

    # Include TPM2 helpers
    . "${BALENA_ROOT_MOUNTPOINT}"/usr/libexec/os-helpers-tpm2

    # Generate password and encrypt it using the TPM
    TPM="${TPM:-/dev/tpmrm0}"
    if [ -e "$TPM" ]; then
        inform "$TPM will be used for LUKS operations"
        export TPM2TOOLS_TCTI="device:$TPM"
    else
        inform "$TPM not found, falling back to autodetection"
    fi

    # Generate a random passphrase
    PASSPHRASE_FILE="$(mktemp)"
    hw_gen_passphrase > "$PASSPHRASE_FILE"

    # Since we tamper with boot order at the very end (putting balenaOS first), we omit PCR1 here
    # PCR1 is added on first boot since this is the setup we want to lock against
    # It is therefore important to boot the device at least once after provisioning in secure environment to enable the protection
    TPM_RESULT_DIR=$(mktemp -d)
    hw_encrypt_passphrase "$PASSPHRASE_FILE" "0,2,3" "$TPM_RESULT_DIR"

    # Attach the image to a loop device
    LOOP_DEVICE=$(losetup --find --show --partscan "/opt/$BALENA_IMAGE")
    LOOP_DEVICE_NAME="${LOOP_DEVICE#/dev/}"

    # Repartition the new drive
    report_progress 0 "Starting flashing balenaOS on internal media"
    inform "Repartitioning $internal_dev for disk encryption"

    # Align partition sizes to multiples of 4MB
    PART_SIZE_ALIGN=$[4 * 1024 * 1024]

    # Wipe the existing partition table and create a blank one
    dd if=/dev/zero of="/dev/$internal_dev" bs=4M count=1
    # Regardless of what the original image uses we always want GPT for secure boot + LUKS
    # Though in practice MBR would work as well in most cases, it is not globally guaranteed
    # and it is much harder to operate on due to the necessity of an extended partition
    parted "/dev/$internal_dev" mktable gpt

    inform "Flashing boot partition"
    ORIGINAL_BOOT_PART_ID=$(get_part_number_by_label "$LOOP_DEVICE_NAME" resin-boot)
    ORIGINAL_BOOT_PART_SIZE=$(get_part_size_by_number "$LOOP_DEVICE_NAME" "$ORIGINAL_BOOT_PART_ID" "$PART_SIZE_ALIGN")
    ORIGINAL_BOOT_START=$(get_part_start_by_number "$LOOP_DEVICE_NAME" "$ORIGINAL_BOOT_PART_ID")

    parted "/dev/$internal_dev" unit B mkpart balena-efi "$ORIGINAL_BOOT_START" $["$ORIGINAL_BOOT_START" + "$ORIGINAL_BOOT_PART_SIZE" - 1]

    EFI_PART_ID=$(get_part_number_by_label "$LOOP_DEVICE_NAME" resin-boot)

    PART_PREFIX=""
    if [ -e "/dev/${internal_dev}p${EFI_PART_ID}" ]; then
        PART_PREFIX="p"
    fi

    dd if="${LOOP_DEVICE}p${ORIGINAL_BOOT_PART_ID}" of="/dev/${internal_dev}${PART_PREFIX}${EFI_PART_ID}" bs=4M
    FLASHED="$ORIGINAL_BOOT_PART_SIZE"

    # Relabel former boot partition
    fatlabel "/dev/${internal_dev}${PART_PREFIX}${EFI_PART_ID}" "balena-efi"

    # Find parition IDs
    ROOTA_PART_ID=$(get_part_number_by_label "$LOOP_DEVICE_NAME" resin-rootA)
    ROOTB_PART_ID=$(get_part_number_by_label "$LOOP_DEVICE_NAME" resin-rootB)
    STATE_PART_ID=$(get_part_number_by_label "$LOOP_DEVICE_NAME" resin-state)
    DATA_PART_ID=$(get_part_number_by_label "$LOOP_DEVICE_NAME" resin-data)

    # Find partition sizes
    BOOT_PART_SIZE=$(get_part_size_by_number "$LOOP_DEVICE_NAME" "$EFI_PART_ID" "$PART_SIZE_ALIGN")
    ROOTA_PART_SIZE=$(get_part_size_by_number "$LOOP_DEVICE_NAME" "$ROOTA_PART_ID" "$PART_SIZE_ALIGN")
    ROOTB_PART_SIZE=$(get_part_size_by_number "$LOOP_DEVICE_NAME" "$ROOTB_PART_ID" "$PART_SIZE_ALIGN")
    STATE_PART_SIZE=$(get_part_size_by_number "$LOOP_DEVICE_NAME" "$STATE_PART_ID" "$PART_SIZE_ALIGN")
    DATA_PART_SIZE=$(get_part_size_by_number "$LOOP_DEVICE_NAME" "$DATA_PART_ID" "$PART_SIZE_ALIGN")

    # Find the beginning of the first partition
    FIRST_PART_ID=$(echo -e "$ROOTA_PART_ID\n$ROOTB_PART_ID\n$STATE_PART_ID\n$DATA_PART_ID" | sort | head -n 1)
    FIRST_PART_START=$(get_part_start_by_number "$LOOP_DEVICE_NAME" "$FIRST_PART_ID")

    # Create new partitions with extra space for LUKS headers
    # LUKS header size is 2MiB
    LUKS_HEADER_SIZE=$[2 * 1024 * 1024]

    BOOT_PART_END=$["$FIRST_PART_START" + "$BOOT_PART_SIZE" + "$LUKS_HEADER_SIZE" - 1]
    parted -s "/dev/$internal_dev" -- unit B mkpart resin-boot "$FIRST_PART_START" "$BOOT_PART_END"

    ROOTA_PART_END=$["$BOOT_PART_END" + "$ROOTA_PART_SIZE" + "$LUKS_HEADER_SIZE"]
    parted -s "/dev/$internal_dev" -- unit B mkpart resin-rootA "$[$BOOT_PART_END + 1]" "$ROOTA_PART_END"

    ROOTB_PART_END=$["$ROOTA_PART_END" + "$ROOTB_PART_SIZE" + "$LUKS_HEADER_SIZE"]
    parted -s "/dev/$internal_dev" -- unit B mkpart resin-rootB "$[$ROOTA_PART_END + 1]" "$ROOTB_PART_END"

    STATE_PART_END=$["$ROOTB_PART_END" + "$STATE_PART_SIZE" + "$LUKS_HEADER_SIZE"]
    parted -s "/dev/$internal_dev" -- unit B mkpart resin-state "$[$ROOTB_PART_END + 1]" "$STATE_PART_END"

    DATA_PART_END=$["$STATE_PART_END" + "$DATA_PART_SIZE" + "$LUKS_HEADER_SIZE"]
    parted -s "/dev/$internal_dev" -- unit B mkpart resin-data "$[$STATE_PART_END + 1]" "$DATA_PART_END"

    for PART_NAME in resin-boot resin-rootA resin-rootB resin-state resin-data; do
        LOOP_PART_ID=$(get_part_number_by_label "$LOOP_DEVICE_NAME" "$PART_NAME")
        INTERNAL_PART_ID=$(get_part_number_by_label "$internal_dev" "$PART_NAME" partlabel)

        PART_DEV="/dev/$internal_dev$PART_PREFIX$INTERNAL_PART_ID"
        inform "Encrypting $PART_DEV"
        cryptsetup luksFormat "$PART_DEV" "$PASSPHRASE_FILE"
        cryptsetup luksOpen "$PART_DEV" "$PART_NAME" --key-file "$PASSPHRASE_FILE"
        DM_DEV="/dev/mapper/$PART_NAME"
        if [ "$PART_NAME" = "resin-boot" ]; then
            # Just create the FS, we will split boot and efi below
            mkfs.ext4 -L "resin-boot" "$DM_DEV"
            continue
        fi

        inform "Flashing $PART_DEV"

        dd_with_progress "${LOOP_DEVICE}p$LOOP_PART_ID" "$DM_DEV" "$FLASHED" "$IMAGE_FILE_SIZE"

        [ "$PART_NAME" = "resin-boot" ] && FLASHED=$["$FLASHED" + "$BOOT_PART_SIZE"]
        [ "$PART_NAME" = "resin-rootA" ] && FLASHED=$["$FLASHED" + "$ROOTA_PART_SIZE"]
        [ "$PART_NAME" = "resin-rootB" ] && FLASHED=$["$FLASHED" + "$ROOTB_PART_SIZE"]
        [ "$PART_NAME" = "resin-state" ] && FLASHED=$["$FLASHED" + "$STATE_PART_SIZE"]
        [ "$PART_NAME" = "resin-data" ] && FLASHED=$["$FLASHED" + "$DATA_PART_SIZE"]

        sync "$DM_DEV"
    done

    rm -f "$PASSPHRASE_FILE"
    losetup -d "$LOOP_DEVICE"
else
    report_progress 0 "Starting flashing balenaOS on internal media"
    dd_with_progress "${BALENA_ROOT_MOUNTPOINT}/opt/$BALENA_IMAGE" "/dev/$internal_dev" 0 "$IMAGE_FILE_SIZE"
fi

sync

# Trigger udev
partprobe /dev/"$internal_dev"
udevadm trigger
udevadm settle

# Flash bootloader(s)
if [ -n "$BOOTLOADER_FLASH_DEVICE" ]; then
    if [ -n "$BOOTLOADER_IMAGE" ] && [ -n "$BOOTLOADER_BLOCK_SIZE_OFFSET" ]; then
        dd if="${EXTERNAL_DEVICE_BOOT_PART_MOUNTPOINT}/${BOOTLOADER_IMAGE}" of="/dev/${BOOTLOADER_FLASH_DEVICE}" bs="${BOOTLOADER_BLOCK_SIZE_OFFSET}" seek="${BOOTLOADER_SKIP_OUTPUT_BLOCKS}"
        inform "Flashed ${BOOTLOADER_IMAGE} to internal flash"
    else
        fail "BOOTLOADER_IMAGE and/or BOOTLOADER_BLOCK_SIZE_OFFSET are not set."
    fi
else
    inform "No need to flash first stage bootloader to a specific device."
fi

if [ -n "$BOOTLOADER_FLASH_DEVICE_1" ]; then
    if [ -n "$BOOTLOADER_IMAGE_1" ] && [ -n "$BOOTLOADER_BLOCK_SIZE_OFFSET_1" ]; then
        dd if="${EXTERNAL_DEVICE_BOOT_PART_MOUNTPOINT}/${BOOTLOADER_IMAGE_1}" of="/dev/${BOOTLOADER_FLASH_DEVICE_1}" bs="${BOOTLOADER_BLOCK_SIZE_OFFSET_1}" seek="${BOOTLOADER_SKIP_OUTPUT_BLOCKS_1}"
        inform "Flashed ${BOOTLOADER_IMAGE_1} to internal flash"
    else
        fail "BOOTLOADER_IMAGE_1 and/or BOOTLOADER_BLOCK_SIZE_OFFSET_1 are not set."
    fi
else
    inform "No need to flash second stage bootloader to a specific device."
fi

# Mount internal device boot partition
mkdir -p $INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT
inform "Mounting internal device boot partition."

if ! mount /dev/disk/by-label/resin-boot $INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT; then
    fail "Failed to mount disk labeled as 'resin-boot'."
fi

if [ "$LUKS" = "1" ]; then
    # Split EFI and boot partitions
    EFI_MOUNT_DIR="$INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT/../efi"
    mkdir -p "$EFI_MOUNT_DIR"
    if ! mount /dev/disk/by-label/balena-efi "$EFI_MOUNT_DIR"; then
        fail "Failed to mount disk labeled as 'balena-efi'."
    fi

    ln -s "../efi/EFI" "$INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT/EFI"

    # Move all non-EFI files to boot partition
    for FILE in "$EFI_MOUNT_DIR/"*; do
        if [ "$FILE" = "$EFI_MOUNT_DIR/EFI" ]; then
            continue
        fi

        mv "$FILE" "$INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT/"
    done

    # Store files necessary for TPM decryption to the EFI partitions
    mv "$TPM_RESULT_DIR/persistent.ctx" "$EFI_MOUNT_DIR/balena-luks.ctx" && sync
    mv "$TPM_RESULT_DIR/passphrase.enc" "$EFI_MOUNT_DIR/balena-luks.enc" && sync

    rm -rf "$TPM_RESULT_DIR"

    # Emulate a stage2 bootloader
    # At this point just copy the flasher kernel to EFI partition
    # TODO: Remove or replace by a proper stage2 bootloader when that is ready
    cp -a "${BALENA_ROOT_MOUNTPOINT}/boot/bzImage" "${BALENA_ROOT_MOUNTPOINT}/boot/bzImage.sig" ${EFI_MOUNT_DIR}

    if [ -f "$EXTERNAL_DEVICE_BOOT_PART_MOUNTPOINT/$INTERNAL_DEVICE_BOOTLOADER_CONFIG_LUKS" ]; then
        INTERNAL_DEVICE_BOOTLOADER_CONFIG="$INTERNAL_DEVICE_BOOTLOADER_CONFIG_LUKS"
    fi
fi

# Copy custom splash dir
mkdir -p "$INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT/$SPLASH_DIRNAME"
cp -r $EXTERNAL_DEVICE_BOOT_PART_MOUNTPOINT/$SPLASH_DIRNAME/* $INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT/$SPLASH_DIRNAME
# Copy Network Manager connection files
CONFIG_NM="${BALENA_BOOT_MOUNTPOINT}/system-connections/"
if [ -d "$CONFIG_NM" ]; then
    inform "Transferring system connections on the internal device."
    rm -rf "$INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT/system-connections/"
    cp -rvf "$CONFIG_NM" "$INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT"
else
    inform "No system connections found to transfer on the internal device."
fi
# Copy proxy configuration files
CONFIG_PROXY="${BALENA_BOOT_MOUNTPOINT}/system-proxy/"
if [ -d "$CONFIG_PROXY" ]; then
    inform "Transferring proxy configuration on the internal device."
    rm -rf "$INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT/system-proxy/"
    cp -rvf "$CONFIG_PROXY" "$INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT"
else
    inform "No proxy configuration found to transfer on the internal device."
fi
# Copy bootloader config file
if [ -n "${INTERNAL_DEVICE_BOOTLOADER_CONFIG}" ] && [ -f "${EXTERNAL_DEVICE_BOOT_PART_MOUNTPOINT}/${INTERNAL_DEVICE_BOOTLOADER_CONFIG}" ]; then
        if [[ -z "${INTERNAL_DEVICE_BOOTLOADER_CONFIG_PATH}" ]]; then
            fail "INTERNAL_DEVICE_BOOTLOADER_CONFIG needs INTERNAL_DEVICE_BOOTLOADER_CONFIG_PATH to be set."
        fi

        cp "$EXTERNAL_DEVICE_BOOT_PART_MOUNTPOINT/$INTERNAL_DEVICE_BOOTLOADER_CONFIG" "$INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT/$INTERNAL_DEVICE_BOOTLOADER_CONFIG_PATH"
        if [ -f "$EXTERNAL_DEVICE_BOOT_PART_MOUNTPOINT/$INTERNAL_DEVICE_BOOTLOADER_CONFIG.sig" ]; then
            cp "$EXTERNAL_DEVICE_BOOT_PART_MOUNTPOINT/$INTERNAL_DEVICE_BOOTLOADER_CONFIG.sig" "$INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT/$INTERNAL_DEVICE_BOOTLOADER_CONFIG_PATH.sig"
        fi

        if [ -n "${INTERNAL_DEVICE_BOOTLOADER_LEGACY_CONFIG_PATH}" ]; then
            cp "$EXTERNAL_DEVICE_BOOT_PART_MOUNTPOINT/$INTERNAL_DEVICE_BOOTLOADER_CONFIG" "$INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT/$INTERNAL_DEVICE_BOOTLOADER_LEGACY_CONFIG_PATH"
        fi
fi

# Copy resinOS bootloader config file
if [ -f "${EXTERNAL_DEVICE_BOOT_PART_MOUNTPOINT}/${BALENA_BOOTLOADER_CONFIG}" ]; then
        cp $EXTERNAL_DEVICE_BOOT_PART_MOUNTPOINT/$BALENA_BOOTLOADER_CONFIG $INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT
fi

# Give a chance for the device to register
STARTTIME=$(date +%s)
ENDTIME="$STARTTIME"
TIMEOUT=10
while [ "$(systemctl is-active resin-device-register.service)" != "active" ]
do
    if [ $((ENDTIME - STARTTIME)) -le $TIMEOUT ]; then
        sleep 1 && ENDTIME=$((ENDTIME + 1))
    else
        inform "Timeout while waiting for register to finish. No network?"
        break
    fi
done

# Copy json configuration file from external (flasher) to the internal (booting) device
cp -rvf "$CONFIG_PATH" "$INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT"

if [ "$LUKS" = "1" ]; then
    umount "$EFI_MOUNT_DIR"
fi

umount $INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT

sync

inform "Board specific flash procedure..."
"${BALENA_ROOT_MOUNTPOINT}"/usr/bin/resin-init-flasher-board

if [ "$LUKS" = "1" ]; then
    for PART_NAME in resin-boot resin-rootA resin-rootB resin-state resin-data; do
        cryptsetup luksClose "$PART_NAME"
    done
fi

report_progress 100 "Post-Provisioning"

POWER_DOWN=${POWER_DOWN:-"shutdown -h now"}
inform "Powering down ..."
${POWER_DOWN}

exit 0
