#!/bin/sh

set -e

. /usr/sbin/resin-vars

if [ "$PERSISTENT_LOGGING" == "yes" ]; then
    echo "[INFO] Configure persistent logs in /mnt/conf/root-overlay/var/log/journal"
    echo -e "[Journal]\nStorage=persistent\n" > /etc/systemd/journald.conf.d/resin-logs.conf
elif [ "$PERSISTENT_LOGGING" == "no" ]; then
    echo "[INFO] Configure volatile logs in /run/log/journal"
    echo -e "[Journal]\nStorage=volatile\n" > /etc/systemd/journald.conf.d/resin-logs.conf
fi

exit 0
