#!/bin/sh
set -e

. /usr/sbin/resin-vars

if [ "$PERSISTENT_LOGGING" == "yes" ]; then
    echo "[INFO] Configure persistent logs in /mnt/conf/root-overlay/var/log/journal"
    sed -ei 's/Storage=.*/Storage=peristent/g' /etc/systemd/journald.conf
    exit 0
fi

if [ "$PERSISTENT_LOGGING" == "no" ]; then
    echo "[INFO] Configure volatile logs in /run/log/journal"
    sed -ei 's/Storage=.*/Storage=volatile/g' /etc/systemd/journald.conf
    exit 0
fi
