#!/bin/bash

added_servers_file=/tmp/chrony_added_dhcp_ntp_servers

interface=$1
action=$2

case "$action" in
	dhcp4-change|up|connectivity-change)
	# Run resin-ntp-config to update chronyc from ntp servers in config.json
	/usr/bin/resin-ntp-config

	if [[ -n $DHCP4_NTP_SERVERS ]]; then
		# Tell chronyd to use this server
		for ntp in ${DHCP4_NTP_SERVERS}; do
			/usr/bin/chronyc add server $ntp || true
		done
		# Save the ntp server we received and interface information to a file
		echo "resin_$interface=\""""$DHCP4_NTP_SERVERS""\" >> $added_servers_file
	fi
	;;
	down)
		# Read ntp server information from file into env variables
		. $added_servers_file
		eval ntp_connection=\$"resin_$interface"

		# Delete the ntp server for that interface from file
		sed -i "/resin_$interface/d" $added_servers_file

		# Tell chronyd to remove this server
		for ntp in ${ntp_connection}; do
			# Only delete the server if it isn't being added by some other interface
			if ! grep -q "$ntp" $added_servers_file; then
				/usr/bin/chronyc delete $ntp || true
			fi

		done

	;;
	*)
	;;
esac
