# Auto-Generated by cargo-bitbake 0.3.12
#
inherit balena_cargo

# If this is git based prefer versioned ones if they exist
# DEFAULT_PREFERENCE = "-1"

# how to get healthdog could be as easy as but default to a git checkout:
# SRC_URI += "crate://crates.io/healthdog/1.0.6"
SRC_URI += "git://github.com/balena-os/healthdog-rs.git;protocol=https;nobranch=1"
SRCREV = "37f9dbb37a399e5548fe47477ddd027bb846212d"
S = "${WORKDIR}/git"
CARGO_SRC_DIR = ""


# please note if you have entries that do not begin with crate://
# you must change them to how that package can be fetched
SRC_URI += " \
    crate://crates.io/bitflags/1.2.1 \
    crate://crates.io/cc/1.0.46 \
    crate://crates.io/cfg-if/0.1.10 \
    crate://crates.io/cstr-argument/0.0.2 \
    crate://crates.io/errno-dragonfly/0.1.1 \
    crate://crates.io/errno/0.2.4 \
    crate://crates.io/exec/0.3.1 \
    crate://crates.io/gcc/0.3.55 \
    crate://crates.io/getopts/0.2.21 \
    crate://crates.io/libc/0.2.65 \
    crate://crates.io/libsystemd-sys/0.2.2 \
    crate://crates.io/log/0.4.8 \
    crate://crates.io/memchr/1.0.2 \
    crate://crates.io/nix/0.15.0 \
    crate://crates.io/pkg-config/0.3.16 \
    crate://crates.io/systemd/0.4.0 \
    crate://crates.io/unicode-width/0.1.6 \
    crate://crates.io/utf8-cstr/0.1.6 \
    crate://crates.io/void/1.0.2 \
    crate://crates.io/winapi-i686-pc-windows-gnu/0.4.0 \
    crate://crates.io/winapi-x86_64-pc-windows-gnu/0.4.0 \
    crate://crates.io/winapi/0.3.8 \
"

SRC_URI[bitflags-1.2.1.sha256sum] = "cf1de2fe8c75bc145a2f577add951f8134889b4795d47466a54a5c846d691693"
SRC_URI[cc-1.0.46.sha256sum] = "0213d356d3c4ea2c18c40b037c3be23cd639825c18f25ee670ac7813beeef99c"
SRC_URI[cfg-if-0.1.10.sha256sum] = "4785bdd1c96b2a846b2bd7cc02e86b6b3dbf14e7e53446c4f54c92a361040822"
SRC_URI[cstr-argument-0.0.2.sha256sum] = "514570a4b719329df37f93448a70df2baac553020d0eb43a8dfa9c1f5ba7b658"
SRC_URI[errno-dragonfly-0.1.1.sha256sum] = "14ca354e36190500e1e1fb267c647932382b54053c50b14970856c0b00a35067"
SRC_URI[errno-0.2.4.sha256sum] = "c2a071601ed01b988f896ab14b95e67335d1eeb50190932a1320f7fe3cadc84e"
SRC_URI[exec-0.3.1.sha256sum] = "886b70328cba8871bfc025858e1de4be16b1d5088f2ba50b57816f4210672615"
SRC_URI[gcc-0.3.55.sha256sum] = "8f5f3913fa0bfe7ee1fd8248b6b9f42a5af4b9d65ec2dd2c3c26132b950ecfc2"
SRC_URI[getopts-0.2.21.sha256sum] = "14dbbfd5c71d70241ecf9e6f13737f7b5ce823821063188d7e46c41d371eebd5"
SRC_URI[libc-0.2.65.sha256sum] = "1a31a0627fdf1f6a39ec0dd577e101440b7db22672c0901fe00a9a6fbb5c24e8"
SRC_URI[libsystemd-sys-0.2.2.sha256sum] = "d7b98458cd04a5c3aacba6f1a3a3c4b9abcb0ae4d66a055eee502e0d52dc226b"
SRC_URI[log-0.4.8.sha256sum] = "14b6052be84e6b71ab17edffc2eeabf5c2c3ae1fdb464aae35ac50c67a44e1f7"
SRC_URI[memchr-1.0.2.sha256sum] = "148fab2e51b4f1cfc66da2a7c32981d1d3c083a803978268bb11fe4b86925e7a"
SRC_URI[nix-0.15.0.sha256sum] = "3b2e0b4f3320ed72aaedb9a5ac838690a8047c7b275da22711fddff4f8a14229"
SRC_URI[pkg-config-0.3.16.sha256sum] = "72d5370d90f49f70bd033c3d75e87fc529fbfff9d6f7cccef07d6170079d91ea"
SRC_URI[systemd-0.4.0.sha256sum] = "daf2fd2d346d2dfb5fdc5f47b355f60dcfc35f5ee3e89e64e7ae2849ec8792a5"
SRC_URI[unicode-width-0.1.6.sha256sum] = "7007dbd421b92cc6e28410fe7362e2e0a2503394908f417b68ec8d1c364c4e20"
SRC_URI[utf8-cstr-0.1.6.sha256sum] = "55bcbb425141152b10d5693095950b51c3745d019363fc2929ffd8f61449b628"
SRC_URI[void-1.0.2.sha256sum] = "6a02e4885ed3bc0f2de90ea6dd45ebcbb66dacffe03547fadbb0eeae2770887d"
SRC_URI[winapi-i686-pc-windows-gnu-0.4.0.sha256sum] = "ac3b87c63620426dd9b991e5ce0329eff545bccbbb34f3be09ff6fb6ab51b7b6"
SRC_URI[winapi-x86_64-pc-windows-gnu-0.4.0.sha256sum] = "712e227841d057c1ee1cd2fb22fa7e5a5461ae8e48fa2ca79ec42cfc1931183f"
SRC_URI[winapi-0.3.8.sha256sum] = "8093091eeb260906a183e6ae1abdba2ef5ef2257a21801128899c3fc699229c6"


# FIXME: update generateme with the real MD5 of the license file
LIC_FILES_CHKSUM = " \
    file://LICENSE;md5=3bfd34238ccc26128aef96796a8bbf97 \
"

SUMMARY = "Helper program that connects external periodic heathchecks with systemd's watchdog support"
HOMEPAGE = "https://github.com/resin-os/healthdog-rs.git"
LICENSE = "Apache-2.0"

# includes this file if it exists but does not fail
# this is useful for anything you may want to override from
# what cargo-bitbake generates.
include healthdog-${PV}.inc
include healthdog.inc
