#!/bin/bash
set -e
set -o pipefail

source /usr/sbin/resin-vars

if [ ! -f $CONFIG_PATH ]; then
    echo "resin-net-config: $CONFIG_PATH does not exist."
    exit 1
fi

if cat "$CONFIG_PATH" | jq -e -r '.files["network/settings"]'; then
	rm -rf /var/lib/connman/*
	mkdir -p /var/lib/connman

	cat $CONFIG_PATH | jq -r '.files["network/settings"] // ""' > /var/lib/connman/settings
	if cat "$CONFIG_PATH" | jq -e -r '.files["network/ethernet.config"]'; then
		cat $CONFIG_PATH | jq -r '.files["network/ethernet.config"] // ""' > /var/lib/connman/ethernet.config
	fi

	if cat "$CONFIG_PATH" | jq -e -r '.files["network/network.config"]'; then
		cat $CONFIG_PATH | jq -r '.files["network/network.config"] // ""' > /var/lib/connman/network.config
	fi
fi
