#!/bin/sh

#
# Script which configures the resinOS_uEnv,txt to use an updated root index
#

set -o errexit

. /usr/sbin/balena-config-vars
. /usr/libexec/os-helpers-fs

DURING_UPDATE=${DURING_UPDATE:-0}

if [ "$DURING_UPDATE" = "1" ]; then
	SYSROOT="/mnt/sysroot/inactive"
else
	SYSROOT="/mnt/sysroot/active"
fi

new_part_idx=$(get_mount_partition_index "${SYSROOT}")

printf "[INFO] Switching uboot root partition index to %s..." "$new_part_idx..."
tmpfile="$(mktemp)"
echo "resin_root_part=$new_part_idx" > ${tmpfile}
echo "upgrade_available=$DURING_UPDATE" >> ${tmpfile}
"${MV}" "${tmpfile}" "/mnt/boot/resinOS_uEnv.txt"
# It is possible to get into a strange state with multiple bootcount.env files so use a delimiter to delete them all.
# See https://github.com/snapcore/snapd/pull/5145 for more detail
rm -f /mnt/boot/*bootcount.env* || true
printf " done.\n"
