#!/bin/sh

set -x

#
# Script which configures the grub.cfg to use an updated root index
#

set -o errexit

. /usr/sbin/balena-config-vars

verifyMd5sum() {
  if [ "$1" = "$3" ] ; then return 1; fi
}

getSize() {
  echo $(du -sb "$1" | awk '{print $1}')
}

DURING_UPDATE=${DURING_UPDATE:-0}

if [ "$DURING_UPDATE" = "1" ]; then
    SYSROOT="/mnt/sysroot/inactive"
else
    SYSROOT="/mnt/sysroot/active"
fi

new_part=$(findmnt --noheadings --canonicalize --output SOURCE $SYSROOT -t ext4)
blockdev=$(basename "$new_part")
new_part_idx=$(cat "/sys/class/block/$blockdev/partition")
new_part_label=$(blkid "$new_part" | awk '{print $2}' | cut -d'"' -f 2)

printf "[INFO] Switching root partition to %s...\n" "$new_part_label..."

# flash legacy grub only if we do not support UEFI
if [ ! -d /sys/firmware/efi ] ; then
    # Remove EFI
    rm -rf "$BALENA_BOOT_MOUNTPOINT/EFI" || true

    MBR=512
    reservedMBR=66
    sourcePath="/resin-boot/grub/"
    device="/dev/$(findmnt --noheadings --canonicalize --output SOURCE /mnt/sysroot/active | xargs lsblk -no pkname)"

    firstBootloader=boot.img
    secondBootloader=core.img

    md5sum_diskFirstBootloader=$(dd if=$device bs=1 count=$(getSize "$sourcePath$firstBootloader") | md5sum)
    md5sum_diskSecondBootloader=$(dd if=$device skip=$MBR bs=1 count=$(getSize "$sourcePath$secondBootloader") | md5sum)

    if verifyMd5sum $(md5sum $sourcePath$firstBootloader) $md5sum_diskFirstBootloader; then
        dd if="$sourcePath$firstBootloader" of="$device" conv=fdatasync bs=1 count=$(expr $MBR - $reservedMBR)
    fi
    if verifyMd5sum $(md5sum $sourcePath$secondBootloader) $md5sum_diskSecondBootloader; then
        dd if="$sourcePath$secondBootloader" of="$device" conv=fdatasync bs=1 seek=$MBR
    fi
else
    # Remove legacy grub
    rm -rf "$BALENA_BOOT_MOUNTPOINT/grub" || true
fi

grub_cfg=$(find $BALENA_BOOT_MOUNTPOINT -name grub.cfg)
grub_env=$(find $BALENA_BOOT_MOUNTPOINT -name grubenv)

tmpfile=$(mktemp)
if  "${CAT}" "$grub_env" | grep -q upgrade_available; then
    printf "[INFO] Automated Rollback support in grub.cfg detected \n"
    "${CAT}" "$grub_env" | sed "s#resin_root_part=.*#resin_root_part="$new_part_idx"#g" > "${tmpfile}"
    "${CAT}" "${tmpfile}" | sed "s#upgrade_available=.*#upgrade_available="$DURING_UPDATE"#g" > "${grub_env}.new"
    "${CAT}" "${grub_env}.new" | sed "s#bootcount=.*#bootcount=0#g" > "${tmpfile}"
    "${MV}" "${tmpfile}" "${grub_env}.new"
    sync_file="$grub_env"
else
    printf "[INFO] Automated Rollback is not supported by grub config file for this device \n"
    "${CAT}" "$grub_cfg" | sed "s/resin-root./${new_part_label}/" > "${tmpfile}"
    "${MV}" "${tmpfile}" "${grub_env}.new"
    sync_file="$grub_cfg"
fi

sync -f $(dirname "$sync_file")
"${MV}" "$sync_file".new "$sync_file"
sync -f $(dirname "$sync_file")
printf "[INFO] Switch root done.\n"
