#!/bin/sh

#
# Script which configures the resinOS_uEnv,txt to use an updated root index
#

set -o errexit

DURING_UPDATE=${DURING_UPDATE:-0}

if [ "$DURING_UPDATE" = "1" ]; then
	SYSROOT="/mnt/sysroot/inactive"
else
	SYSROOT="/mnt/sysroot/active"
fi

new_part=$(findmnt --noheadings --canonicalize --output SOURCE $SYSROOT)
blockdev=$(basename "$new_part")
new_part_idx=$(cat "/sys/class/block/$blockdev/partition")

# Convert to hex as u-boot expects hex partition numbers. Especially needed for jetson devices
new_part_idx=$(printf "%x" $new_part_idx)

printf "[INFO] Switching uboot root partition index to %s..." "$new_part_idx..."
echo "resin_root_part=$new_part_idx" > /mnt/boot/resinOS_uEnv.txt.new
echo "upgrade_available=$DURING_UPDATE" >> /mnt/boot/resinOS_uEnv.txt.new
rm -f /mnt/boot/bootcount.env || true

sync -f /mnt/boot
mv /mnt/boot/resinOS_uEnv.txt.new /mnt/boot/resinOS_uEnv.txt
sync -f /mnt/boot
printf " done.\n"
