#!/bin/bash
set -e
set -o pipefail

if [ -z "$CONFIG_PATH" ]; then
	echo "Please set CONFIG_PATH environment variable."
	exit 1
fi

if cat "$CONFIG_PATH" | jq -e -r '.files["network/network.config"]'; then
	rm -rf /var/lib/connman/*
	mkdir -p /var/lib/connman

	cat $CONFIG_PATH | jq -r '.files["network/network.config"] // ""' > /var/lib/connman/network.config
	cat $CONFIG_PATH | jq -r '.files["network/settings"] // ""' > /var/lib/connman/settings
fi
