#!/bin/sh

if [ ! -e /boot/config.json ]; then
	/usr/bin/init-bbb-flasher.sh
fi

mount -o bind,rw /mnt/data-disk/docker /var/lib/docker
mount -o bind,rw /mnt/data-disk/resin-data /resin-data
mkdir -p /tmp/.docker
mount -o bind,rw /tmp/.docker /.docker

docker --restart=false -s btrfs --dns=8.8.8.8 --dns=8.8.4.4 -d -g /var/lib/docker &

# Wait for docker to become ready
echo "Waiting for docker to become ready.."
while [ ! -S /var/run/docker.sock ]
do
	sleep 1
done

# Run supervisor  
echo "Starting resin/armhfv7-supervisor.."  
docker run --privileged -d -v /var/run/docker.sock:/run/docker.sock -e SUPERVISOR_IMAGE=resin/armhfv7-supervisor -e CONFIG_MOUNT_POINT=/boot/config.json -e LED_FILE=/sys/class/leds/beaglebone\:green\:usr3/brightness -e API_ENDPOINT=https://staging.resin.io -e REGISTRY_ENDPOINT=registry.staging.resin.io -e PUBNUB_SUBSCRIBE_KEY=sub-c-bbc12eba-ce4a-11e3-9782-02ee2ddab7fe -e PUBNUB_PUBLISH_KEY=pub-c-6cbce8db-bfd1-4fdf-a8c8-53671ae2b226 -e MIXPANEL_TOKEN=cb974f32bab01ecc1171937026774b18 resin/armhfv7-supervisor /start

source /etc/resin.conf
export API_ENDPOINT CONFIG_PATH
resin-device-progress "" "Finished" || true

while [ ! -d /resin-data/resin-supervisor ]
do
        sleep 1
done

# Disable power management.
iwconfig wlan0 power off

# Open socket for supervisor to connect to the host
bash -c 'while true; do rm -f /resin-data/resin-supervisor/host; socat UNIX-LISTEN:/resin-data/resin-supervisor/host EXEC:/bin/bash,pty,setsid,setpgid,stderr,ctty; done' &
