#!/bin/sh

# Copyright 2023 Balena Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# Generic networkmanager device connectivity event dispatcher
#

. /usr/libexec/os-helpers-logging

case "${2}" in
	up | down | connectivity-change | device-connectivity-change)
		if [ -d "/etc/NetworkManager/dispatcher.d/${2}.d" ]; then
			info "Running dispatchers for ${2}"
			run-parts -a "${1}" -a "${2}" "/etc/NetworkManager/dispatcher.d/${2}.d"
		fi
		;;
	*)
		# Do nothing
		;;
esac
