#!/bin/bash

# Parse arguments
while [[ $# > 1 ]]; do
    key="$1"
    case $key in
        -h|--help)
            echo "Usage: $0 [options]"
            echo -e "\t-c CONFIG_PATH\tArgument passed to resin-vars"
            echo -e "\t-p PERCENTAGE\tExample: 50"
            echo -e "\t-s STATE\tExample: Loading filesystem"
            echo "Requires API_ENDPOINT and CONFIG_PATH environment variables to be set."
            exit 0
            ;;
        -c|--config-path)
            RESIN_VARS_ARGS="$RESIN_VARS_ARGS --config-path $2"
            shift
            ;;
        -p|--percentage)
            PERCENTAGE=$2
            shift
            ;;
        -s|--state)
            STATE=$2
            shift
            ;;
        *)
            # unknown option
            ;;
    esac
    shift
done

source /usr/sbin/resin-vars $RESIN_VARS_ARGS

echo "-- $0 $PERCENTAGE $STATE $API_ENDPOINT $CONFIG_PATH" >> /var/log/provisioning-progress.log
if [ -z "$PERCENTAGE" -o -z "$STATE" -o -z "$API_ENDPOINT" -o -z "$CONFIG_PATH" ]; then
    echo "ERROR: Needed variables not provided."
    exit 1
fi

if [ `jq ".registered_at | length" $CONFIG_PATH` -eq 0 ]; then
    echo "Device registration not complete, provisioning progress cannot be reported."
    exit 1
fi

if [ `jq ".deviceId | length" $CONFIG_PATH` -eq 0 ]; then
    echo "Device id (deviceId) missing from config file, provisioning progress cannot be reported."
    exit 1
fi

read api_key device_id <<<$(jq -r '.apiKey,.deviceId' $CONFIG_PATH)

curl -s -X PATCH "$API_ENDPOINT/ewa/device($device_id)?apikey=$api_key" \
     -o "/var/log/provisioning-progress-curl-$PERCENTAGE.log" \
     --data-urlencode "provisioning_progress=$PERCENTAGE" \
     --data-urlencode "provisioning_state=$STATE"
