#!/bin/sh

if [ ! -e /boot/config.json ]; then
        /usr/bin/init-bbb-flasher.sh
fi

mount -o bind,rw /mnt/data-disk/docker /var/lib/docker
mount -o bind,rw /mnt/data-disk/resin-data /resin-data
mkdir -p /tmp/.docker
mount -o bind /tmp/.docker /.docker

docker --restart=false -s btrfs --dns=8.8.8.8 --dns=8.8.4.4 -d -g /var/lib/docker  > /dev/null 2>&1 &

# Wait for docker to become ready
echo "Waiting for docker to become ready.."
while [ ! -S /var/run/docker.sock ]
do
	sleep 1
done

# Run supervisor
echo "Starting resin/armhfv7-supervisor.."
docker run --privileged -d -v /var/run/docker.sock:/run/docker.sock -e SUPERVISOR_IMAGE=resin/armhfv7-supervisor -e CONFIG_MOUNT_POINT=/boot/config.json -e LED_FILE=/sys/class/leds/beaglebone\:green\:usr3/brightness resin/armhfv7-supervisor /start

source /etc/resin.conf
export API_ENDPOINT CONFIG_PATH
resin-device-progress "" "Finished" || true

while [ ! -d /resin-data/resin-supervisor ]
do
	sleep 1
done

# Disable power management.
iwconfig wlan0 power off

# Open socket for supervisor to connect to the host
bash -c 'while true; do rm -f /resin-data/resin-supervisor/host; socat UNIX-LISTEN:/resin-data/resin-supervisor/host EXEC:/bin/bash,pty,setsid,setpgid,stderr,ctty; done' &
