#!/bin/bash

help () {
    cat << EOF
Script for setting resin shell environment
resin-vars [options]

Options:
    -h, --help
        Display this help and exit.

    -c, --config-path CONFIG_PATH
        Use a non default config.json file.
        Default: /mnt/boot/config.json
EOF
}

# Parse arguments
while [ "$#" -gt "0" ]; do
    key=$1
    case $key in
        -h|--help)
            help
            exit 0
            ;;
        -c|--config-path)
            CONFIG_PATH=$2
            shift
            ;;
        *)
            echo "[WARNING] $0 : Argument '$1' unknown. Ignoring."
            ;;
    esac
    shift
done

# Resin-boot mountpoint
BOOT_MOUNTPOINT="/mnt/boot"

# Default values
if [ -z "$CONFIG_PATH" ]; then
    CONFIG_PATH=$BOOT_MOUNTPOINT/config.json
fi

# If config.json provides redefinitions for our vars let us rewrite their
# runtime value
if [ -f $CONFIG_PATH ]; then
    API_ENDPOINT=$(jq --raw-output ".apiEndpoint // empty" $CONFIG_PATH)
    LISTEN_PORT=$(jq --raw-output ".listenPort // empty" $CONFIG_PATH)
    MIXPANEL_TOKEN=$(jq --raw-output ".mixpanelToken // empty" $CONFIG_PATH)
    PUBNUB_PUBLISH_KEY=$(jq --raw-output ".pubnubPublishKey // empty" $CONFIG_PATH)
    PUBNUB_SUBSCRIBE_KEY=$(jq --raw-output ".pubnubSubscribeKey // empty" $CONFIG_PATH)
    REGISTRY_ENDPOINT=$(jq --raw-output ".registryEndpoint // empty" $CONFIG_PATH)
    VPN_ENDPOINT=$(jq --raw-output ".vpnEndpoint // empty" $CONFIG_PATH)
    DELTA_ENDPOINT=$(jq --raw-output ".deltaEndpoint // empty" $CONFIG_PATH)
    CONFIG_HOSTNAME=$(jq --raw-output ".hostname // empty" $CONFIG_PATH)
    PERSISTENT_LOGGING=$(jq --raw-output ".persistentLogging // empty" $CONFIG_PATH)
    COUNTRY=$(jq --raw-output ".country // empty" $CONFIG_PATH)
    UUID=$(jq --raw-output ".uuid // empty" $CONFIG_PATH)
    PROVISIONING_API_KEY=$(jq --raw-output ".apiKey // empty" $CONFIG_PATH)
    DEVICE_API_KEY=$(jq --raw-output ".deviceApiKey // empty" $CONFIG_PATH)
    DEVICE_ID=$(jq --raw-output '.deviceId // empty' $CONFIG_PATH)
    USER_ID=$(jq --raw-output '.userId // empty' $CONFIG_PATH)
    APPLICATION_ID=$(jq --raw-output '.applicationId // empty' $CONFIG_PATH)
    DEVICE_TYPE=$(jq --raw-output '.deviceType // empty' $CONFIG_PATH)
    REGISTERED_AT=$(jq --raw-output '.registered_at // empty' $CONFIG_PATH)
    if [ -z "$API_ENDPOINT" -o -z "$LISTEN_PORT" -o -z "$MIXPANEL_TOKEN" -o -z "$PUBNUB_PUBLISH_KEY" -o -z "$PUBNUB_SUBSCRIBE_KEY" -o -z "$REGISTRY_ENDPOINT" -o -z "$VPN_ENDPOINT" ]; then
        echo "[WARNING] $0 : Couldn't read some variables from $CONFIG_PATH"
    fi
    if [ -z "$PERSISTENT_LOGGING" ]; then
        PERSISTENT_LOGGING=false
    fi
else
    echo "[WARNING] $0 : '$CONFIG_PATH' not found."
fi
