#!/bin/sh

set -o errexit

USER_APP_STORAGE="/mnt/data/docker"
HOST_APP_STORAGE="/mnt/sysroot/inactive/balena"

printf "[INFO] balena_migrate_storage: Migrating userapp storage to overlayfs... \n"
env BALENA_A2O_STORAGE_ROOT=$USER_APP_STORAGE a2o-migrate -debug -migrate

printf "[INFO] balena_migrate_storage: Migrating hostapp storage to overlayfs... \n"
env BALENA_A2O_STORAGE_ROOT=$HOST_APP_STORAGE a2o-migrate -debug -migrate

sync -f /mnt/data
sync -f /mnt/sysroot/inactive
