#!/bin/sh

. /usr/libexec/os-helpers-logging
. /usr/sbin/balena-config-vars

DEVELOPMENT_FEATURES_FLAG_FILE="/var/volatile/development-features"

gen_devmode_config() {
	if [ -f "${CONFIG_PATH}" ]; then
		development_mode="$(jq -r ".developmentMode" "${CONFIG_PATH}")"
		if [ "${development_mode}" = "true" ]; then
			authenticated_ssh="$(jq -r ".os.sshKeys" "${CONFIG_PATH}")"
			if [ -n "${authenticated_ssh}" ] && [ "${authenticated_ssh}" != "null" ]; then
				info "Disabling SSH passwordless login on development mode"
				echo "SSHD_OPTS='-f /etc/ssh/sshd_config_development -o PasswordAuthentication=no'" > "${DEVELOPMENT_FEATURES_FLAG_FILE}"
			else
				echo "SSHD_OPTS='-f /etc/ssh/sshd_config_development'" > "${DEVELOPMENT_FEATURES_FLAG_FILE}"
			fi
			echo 'BALENA_DEVELOPMENT_ARGS="-H tcp://0.0.0.0:2375"' >> "${DEVELOPMENT_FEATURES_FLAG_FILE}"
		fi
	fi
}
