#!/bin/bash

set -o pipefail
set -e

source /etc/resin.conf
source /etc/supervisor.conf

image=$1
if [ -z "$image" ]; then
	echo "Usage: $0 IMAGE_NAME [CONTAINER_NAME]"
	echo "Using default IMAGE_NAME - $SUPERVISOR_IMAGE in supervisor.conf"
	image=$SUPERVISOR_IMAGE
fi

rce run -d --privileged --name resin_supervisor \
	--net=host \
	-v /var/run/rce.sock:/run/docker.sock \
	-v "$CONFIG_PATH":/boot/config.json  \
	-v /resin-data/resin-supervisor:/data \
	-v /proc/net/fib_trie:/mnt/fib_trie \
	-v /var/log/supervisor-log:/var/log \
	-v /:/mnt/root \
	-e API_ENDPOINT="$API_ENDPOINT" \
	-e REGISTRY_ENDPOINT="$REGISTRY_ENDPOINT" \
	-e PUBNUB_SUBSCRIBE_KEY="$PUBNUB_SUBSCRIBE_KEY" \
	-e PUBNUB_PUBLISH_KEY="$PUBNUB_PUBLISH_KEY" \
	-e MIXPANEL_TOKEN="$MIXPANEL_TOKEN" \
	-e LED_FILE="$LED_FILE" \
	-e LISTEN_PORT="$LISTEN_PORT" \
	-e SUPERVISOR_IMAGE="$image" \
	$image
