#!/bin/sh
#
# Copyright 2017 Resinio Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# copy over NTP configuration
#

set -e

. /usr/sbin/resin-vars

if [ ! -f "$CONFIG_PATH" ]; then
	echo "resin-ntp-config: $CONFIG_PATH does not exist."
	exit 1
else
	echo "resin-ntp-config: Found config.json in $CONFIG_PATH ."
fi

if [ ! -z "$NTP_SERVERS" ]; then
	cat >/etc/systemd/timesyncd.conf <<EOF
[Time]
NTP=$NTP_SERVERS
EOF
fi

exit 0
