#!/bin/bash

source /usr/sbin/resin-vars
VPN_PORT=443
TMPDIR=/run

if [ ! -f $CONFIG_PATH ]; then
    echo "prepare-openvpn: $CONFIG_PATH - No such file."
    exit 1
fi

while true; do
	if [ `jq ".uuid | length" $CONFIG_PATH` -eq 0 ] || [ `jq ".apiKey | length" $CONFIG_PATH` -eq 0 ]; then
		echo "prepare-openvpn: UUID and/or APIKEY missing from config file, VPN cannot connect"
		sleep 2
	else
		read uuid api_key <<<$(jq -r '.uuid,.apiKey' $CONFIG_PATH)
		echo $uuid > /var/volatile/vpnfile
		echo $api_key >> /var/volatile/vpnfile
		break
	fi
done

mkdir -p $TMPDIR/openvpn

# Create openvpn configuration
sed -e "/remote .*/ c\remote $VPN_ENDPOINT $VPN_PORT" /etc/openvpn/resin.conf > $TMPDIR/openvpn/resin.conf
