#!/bin/sh

set -e

. /usr/sbin/resin-vars

_vpn_port=443
readonly _vpn_port

if [ ! -f $CONFIG_PATH ]; then
	echo "prepare-openvpn: $CONFIG_PATH - No such file."
	exit 1
fi

while :; do
	_uuid=$(jq -r '.uuid' $CONFIG_PATH)
	_api_key=$(jq -r '.apiKey' $CONFIG_PATH)

	if [ "$_uuid" = "null" ] || [ "$_api_key" = "null" ]; then
		echo "prepare-openvpn: UUID and/or APIKEY missing from config file, VPN cannot connect"
		sleep 2
	else
		break
	fi
done

VPNTEMPLATE=${CONFIG_PATH%/*}/system-connections/resin-vpn
VPNFILE=/etc/NetworkManager/system-connections/resin-vpn

sed "s/<<remote>>/$VPN_ENDPOINT/;
     s/<<port>>/$_vpn_port/;
     s/<<user>>/$_uuid/;
     s/<<password>>/$_api_key/" $VPNTEMPLATE > $VPNFILE
