#!/bin/bash
CONFIG_PATH=/mnt/data-disk/config.json

# If config.json provides redefinitions for our vars let us rewrite their
# runtime value
if [ -f $CONFIG_PATH ]
then
    API_ENDPOINT=$(jq --raw-output ".apiEndpoint" $CONFIG_PATH)
    LISTEN_PORT=$(jq --raw-output ".listenPort" $CONFIG_PATH)
    MIXPANEL_TOKEN=$(jq --raw-output ".mixpanelToken" $CONFIG_PATH)
    PUBNUB_PUBLISH_KEY=$(jq --raw-output ".pubnubPublishKey" $CONFIG_PATH)
    PUBNUB_SUBSCRIBE_KEY=$(jq --raw-output ".pubnubSubscribeKey" $CONFIG_PATH)
    REGISTRY_ENDPOINT=$(jq --raw-output ".registryEndpoint" $CONFIG_PATH)
fi
