#!/bin/bash

source /etc/resin.conf

# If config.json provides redefinitions for our vars let us rewrite their
# runtime value
API_ENDPOINT=$(jq ".apiEndpoint // \"$API_ENDPOINT\"" $CONFIG_PATH)
LISTEN_PORT=$(jq ".listenPort // \"$LISTEN_PORT\"" $CONFIG_PATH)
MIXPANEL_TOKEN=$(jq ".mixpanelToken // \"$MIXPANEL_TOKEN\"" $CONFIG_PATH)
PUBNUB_PUBLISH_KEY=$(jq ".pubnubPublishKey // \"$PUBNUB_PUBLISH_KEY\"" $CONFIG_PATH)
PUBNUB_SUBSCRIBE_KEY=$(jq ".pubnubSubscribeKey // \"$PUBNUB_SUBSCRIBE_KEY\"" $CONFIG_PATH)
REGISTRY_ENDPOINT=$(jq ".registryEndpoint // \"$REGISTRY_ENDPOINT\"" $CONFIG_PATH)
