#!/bin/bash

set -ex

SYSROOT="/mnt/sysroot/inactive"

balenad -s=@BALENA_STORAGE@ --data-root="$SYSROOT/balena" -H unix:///var/run/balena-host.sock &
pid=$!
sleep 5

hostapp-update -f /input -n

kill $pid
wait $pid

mkfs.ext4 -F -E lazy_itable_init=0,lazy_journal_init=0 -i 8192 /output
mount /output /media
cp -a --sparse=never "$SYSROOT/." /media
sync -f /media
umount /media
