#!/bin/bash

set -ex

SYSROOT="/mnt/sysroot/inactive"

dockerd -s=@DOCKER_STORAGE@ --data-root="$SYSROOT/docker" -H unix:///var/run/docker-host.sock &
pid=$!
sleep 5

hostapp-update -f /input

kill $pid
wait $pid

mkfs.ext4 -F -E lazy_itable_init=0,lazy_journal_init=0 -i 8192 -d "$SYSROOT" /output
