#!/bin/sh

FREESPACE_LIMIT=10
datapart=$(readlink -f /dev/disk/by-label/resin-data)
datadev=$(lsblk $datapart -n -o PKNAME)

resindataexpander_enabled() {
    # On flasher avoid expanding partition
	if [ -h /dev/disk/by-label/flash-rootA ]; then
		flash_root=$(readlink -f "/dev/disk/by-label/flash-rootA")
		if [ "`echo ${bootparam_root} | cut -c1-5`" = "UUID=" ]; then
			root_uuid=`echo $bootparam_root | cut -c6-`
			root_link="/dev/disk/by-uuid/$root_uuid"
		elif [ "`echo ${bootparam_root} | cut -c1-9`" = "PARTUUID=" ]; then
			root_puuid=`echo $bootparam_root | cut -c10-`
			root_link="/dev/disk/by-partuuid/$root_puuid"
		elif [ "`echo ${bootparam_root} | cut -c1-6`" = "LABEL=" ]; then
			root_label=`echo $bootparam_root | cut -c7-`
			root_link="/dev/disk/by-label/$root_link"
		fi
		if [ "$(readlink -f "$root_link")" == "$flash-root" ]; then
			echo "[INFO] Flasher detected. Avoiding expand partition mechanism."
			return 1
		fi
    fi

    for freespace in $(parted -m /dev/$datadev unit MiB print free | grep free | cut -d: -f4 | sed 's/MiB//g'); do
        if [ $(echo $freespace \> $FREESPACE_LIMIT | bc -l) == "1" ]; then
            return 0
        fi
    done
    return 1
}

resindataexpander_run() {
    info "resindataexpander: Expand extended partition... "
    parted -s /dev/$datadev -- resizepart 4 -1s
    info "resindataexpander: Finished expanding extended partition."
    info "resindataexpander: Expand data partition... "
    parted -s /dev/$datadev -- resizepart 6 -1s
    info "resindataexpander: Finished expanding data partition."

    partprobe
    sync
}
