FROM balenalib/%%BALENA_ARCH%%-alpine:3.18-run

RUN apk add --no-cache git coreutils

COPY entrypoint.sh /usr/bin/entrypoint.sh
RUN chmod +x /usr/bin/entrypoint.sh

ENTRYPOINT ["/usr/bin/entrypoint.sh"]
CMD ["sleep", "infinity"]
