#!/bin/bash

source /usr/sbin/resin-vars

while true; do
	if [ `jq ".uuid | length" $CONFIG_PATH` -eq 0 ]; then
		echo "UUID missing from config file, VPN cannot connect"
		sleep 2
	else
		read uuid api_key <<<$(jq -r '.uuid,.apiKey' $CONFIG_PATH)
		echo $uuid > /var/volatile/vpnfile
		echo $api_key >> /var/volatile/vpnfile
		break
	fi
done

if [ -e /etc/init.d/openvpn ]; then
	/etc/init.d/openvpn start
else
	mkdir -p /var/run/openvpn
	systemctl start openvpn@client.service
fi
