#!/bin/sh

source /etc/resin.conf

if [ ! -e $CONFIG_PATH ]; then
        /usr/bin/init-bbb-flasher.sh
fi

mount -o bind,rw /mnt/data-disk/rce /var/lib/rce
mount -o bind,rw /mnt/data-disk/resin-data /resin-data
mkdir -p /tmp/.rce
mount -o bind /tmp/.rce /.rce
