#!/bin/bash

MOUNT_POINT=/mnt/data-disk

for usage in 0 5 10 15 20; do
	nice -n 19 btrfs balance start -dusage=$usage $MOUNT_POINT
	if [ $? -ne 0 ]; then # Print the following on btrfs balance failure
		echo "Btrfs balance failed while freeing $usage % full block groups"
	fi
done
