name: Compulab IOT-GATE-iMX8PLUS 2G-4G DRAM

on:
  pull_request:
    branches:
      - main
      - master
      # ESR branches glob pattern
      - "[0-9]+.[0-9]+.x"
  pull_request_target:
    branches:
      - main
      - master
      # ESR branches glob pattern
      - "[0-9]+.[0-9]+.x"

jobs:
  yocto:
    name: Yocto
    uses: balena-os/balena-yocto-scripts/.github/workflows/yocto-build-deploy.yml@5c8805dcd0013ca3aab6ec82e094595ad8f6780b # v1.25.28
    # Prevent duplicate workflow executions for pull_request (PR) and pull_request_target (PRT) events.
    # Both PR and PRT will be triggered for the same pull request, whether it is internal or from a fork.
    # This condition will prevent the workflow from running twice for the same pull request while
    # still allowing it to run for all other event types.
    if: (github.event.pull_request.head.repo.full_name == github.repository) == (github.event_name == 'pull_request')
    secrets: inherit
    with:
      # Needed for testing - defaults to production
      deploy-environment: balena-staging.com
      machine: iot-gate-imx8plus
      device-repo: balena-os/balena-iot-gate-imx8plus
      device-repo-ref: master
      # Pin to the current commit
      meta-balena-ref: ${{ github.sha }}
