name: Nvidia Jetson TX2

on:
  pull_request:
    branches:
      - main
      - master
      # ESR branches glob pattern
      - "[0-9]+.[0-9]+.x"
  pull_request_target:
    branches:
      - main
      - master
      # ESR branches glob pattern
      - "[0-9]+.[0-9]+.x"

jobs:
  yocto:
    name: Yocto
    uses: balena-os/balena-yocto-scripts/.github/workflows/yocto-build-deploy.yml@0899d814aa7f25d48825ac701c61e066f7b0c4f5 # v1.25.45
    # Prevent duplicate workflow executions for pull_request (PR) and pull_request_target (PRT) events.
    # Both PR and PRT will be triggered for the same pull request, whether it is internal or from a fork.
    # This condition will prevent the workflow from running twice for the same pull request while
    # still allowing it to run for all other event types.
    if: (github.event.pull_request.head.repo.full_name == github.repository) == (github.event_name == 'pull_request')
    secrets: inherit
    with:
      # Needed for testing - defaults to production
      deploy-environment: balena-staging.com
      machine: jetson-tx2
      device-repo: balena-os/balena-jetson
      device-repo-ref: master
      # Pin to the current commit
      meta-balena-ref: ${{ github.sha }}
